### ISSUE TITLE
Hang on app launch

### ISSUE THREAD

**Issue by flit** [sbarex/SourceCodeSyntaxHighlight#101]
Version: 2.0.10
OS: 11.4 (20F71)
Arch: arm64e

When attempting to launch the app, it hangs indefinitely with the icon bouncing in the dock. It must be force quit. The hang is 100% reproducible. It appears the QL plugin is working ok.

Previous versions ran successfully on the same hardware+OS (just moments before I installed the update).

Erasing preferences and the app's container and cache does not help.

System crash report generated after force quitting the application:
[syntax_highlight_hang_repo.txt](https://github.com/sbarex/SourceCodeSyntaxHighlight/files/6795798/syntax_highlight_hang_repo.txt)

**Comment by sbarex** [comment]
Does the application start using a rosetta? Have you created any personal themes?

**Comment by sbarex** [comment]
Try release 2.0.11.

**Comment by flit** [comment]
That fixed it! Thanks!
