### ISSUE TITLE
support for more autotools files (ma, ac)

### ISSUE THREAD

**Issue by DominusExult** [sbarex/SourceCodeSyntaxHighlight#103]
Could you please suppoort m4 files? https://en.wikipedia.org/wiki/M4_(computer_language) 

mdls -name kMDItemContentType -name kMDItemContentTypeTree /Users/Dominus/Code/snapshots/exult/acinclude.m4
kMDItemContentType     = "dyn.ah62d4rv4ge804ra"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge804ra",
    "public.data"
)

And also ac (as in configure.ac) would be nice, too
 mdls -name kMDItemContentType -name kMDItemContentTypeTree /Users/Dominus/Code/snapshots/exult/configure.ac
kMDItemContentType     = "dyn.ah62d4rv4ge80c22"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge80c22",
    "public.data"
)
Thanks a lot for this plugin!

**Comment by DominusExult** [comment]
right my bad. Newbie here, I was confused by the "Only the formats supported by `highlight` can be managed by this application".

**Comment by sbarex** [comment]
if the m4 format derives from one of those supported, it is still possible to manage it

**Comment by DominusExult** [comment]
I think the m4 and ac are a mixmatch of several, kinda like c code and makefile.
There is a Visual Studio Code plugin (not that it is compatible in any way :)) https://github.com/maelvls/vscode_autotools
