### ISSUE TITLE
Signing error with MacOS 11.6

### ISSUE THREAD

**Issue by gabrielwhite** [sbarex/SourceCodeSyntaxHighlight#108]
After upgrading to MacOS 11.6 I see this error:

<img width="372" alt="Screen Shot 2021-09-13 at 5 44 45 PM" src="https://user-images.githubusercontent.com/955848/133153807-bf842a9e-42dd-4242-97bd-d046d47d6f09.png">

**Comment by sbarex** [comment]
The app is not code signed. For the first play, on the Finder, command click on the icon and choose `open` form the contextual menu. Then confirm to start the app.

For other info see the `readme.md` in this repository, at _Note for downloading the precompiled release_.

**Comment by gabrielwhite** [comment]
Ah, thanks. I guess this isn't preserved in OS upgrades.

**Comment by sbarex** [comment]
It's weird, I just updated and didn't have this problem.
