### ISSUE TITLE
Feature request: Gherkin

### ISSUE THREAD

**Issue by AgingOrange** [sbarex/SourceCodeSyntaxHighlight#109]
Gherkin (which is used by Cucumber (cucumber.io) support would be nice.

kMDItemContentType     = "dyn.ah62d4rv4ge80q3pbsv41e3k"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge80q3pbsv41e3k",
    "public.data"
)

https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md lists support.

Also: How come I only find out about this plugin now? Amazing.

**Comment by sbarex** [comment]
What is the extension used by Gherkin? 
`.gherkin`?

**Comment by AgingOrange** [comment]
Ah, I'm sorry, I should have said that: `.feature`.

**Comment by sbarex** [comment]
Oh, I'm sorry, but I didn't realize you mentioned [highlightjs](https://github.com/highlightjs/highlight.js), but my app uses another engine: [Highlight](http://www.andre-simon.de/doku/highlight/en/highlight.php) that do not support Gherkin. 

On my app, from the about menu, you can see the supported languages.

**Comment by AgingOrange** [comment]
Oh, I guess that's my bad. I saw "highlight" and I assumed …

Any way to have the plugin open files without extension (like README) as text file, or is that a QuickView thing?

**Comment by sbarex** [comment]
Not at the moment. This is something I should work on when I have some time and inspiration. 

For now you can use the old (but still good) [qlstephen](https://github.com/whomwah/qlstephen).
