### ISSUE TITLE
[Tip] Install in User Application Directory

### ISSUE THREAD

**Issue by skoskie** [sbarex/SourceCodeSyntaxHighlight#11]
First thank you so much for building this! It was so needed. 

Second, I was having trouble getting it to work, I think partly because I placed the `.app` in the `/Applications/Utilities` directory initially. But even after I moved it up a level, I still couldn't get it to work. 

#### I moved the application to `~/Applications` and everything worked just fine. 

My guess is that there is more security on apps that are available at the system level. Who knows. I just wanted to share in case anyone else was having a similar issue.

**Comment by hazarek** [comment]
`/Applications` is an illusion on Catalina, read this https://eclecticlight.co/2019/10/08/macos-catalina-boot-volume-layout/

**Comment by sbarex** [comment]
Strange that it doesn't work.
I tried to put it in the utilities folder (the Finder requires authentication to do it) and it works correctly.

Have you checked if the "Source Code Syntax Highlight Quicklook extension" entry is checked in the System preferences / extensions?

**Comment by sbarex** [comment]
Also there is a bug for quicklook extension (not in standalone app) is the application is stored in a path with whitespace or special chars. Fix is coming.
