### ISSUE TITLE
support for sty files

### ISSUE THREAD

**Issue by zhyiyu** [sbarex/SourceCodeSyntaxHighlight#114]
Hi, could you please consider adding syntax highlight support for `sty` files (LaTeX packages are written in this format)? Its syntax is almost exactly the same as for `tex` files. Thanks!

Here is a screen shot for its format (`UTI = org.tug.sty`)

<img width="804" alt="sty" src="https://user-images.githubusercontent.com/26550166/138042522-42c15e39-947e-4bb7-9082-12fc9f6a07ad.png">

**Comment by sbarex** [comment]
Support added on release 2.1.0.
