### ISSUE TITLE
colorize.log

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#118]
After updating it creates colorize.log file on my desktop
<img width="128" alt="log" src="https://user-images.githubusercontent.com/36481442/141689184-3df26805-cfb7-4462-b2d6-64c36893b765.png">
.

**Comment by sbarex** [comment]
debug options is set?

**Comment by hazarek** [comment]
No
<img width="619" alt="Ekran Resmi 2021-11-14 19 56 35" src="https://user-images.githubusercontent.com/36481442/141690465-39279b24-2a29-4168-8a29-408944db5cf9.png">

**Comment by sbarex** [comment]
Fixed on 2.1.1 release.
