### ISSUE TITLE
[Build] How are you linking libLua.dylib?

### ISSUE THREAD

**Issue by rileytwo** [sbarex/SourceCodeSyntaxHighlight#12]
I'm not able to get a successful build unless I embed `libLua.dylib` inside of `SourceCodeSyntaxHighlightXPCService`, under `Frameworks`. I also have to change the install path of `Lua macOS` from `/usr/local/lib` to `@rpath`.

Are you building lua a specific way, or am I just making this too hard on myself? 😅

Thanks!

**Comment by sbarex** [comment]
I think I made a mistake in connecting the git submodule lua and when cloning it dont fetch my customization (creation of a static libs).
Have you execute these commands (especially the last 2 lines) from terminal insede the dir of the main git project?
```
$ git submodule init 
$ git submodule update
$ cd lua4swift
$ git checkout
```

**Comment by rileytwo** [comment]
I did--I was able to build and run the app (pressing `cmd`+`R` in Xcode, or by pressing the play button in the toolbar), but I'm not able to open the app without getting a missing dylib symbol error. It can run inside Xcode, but not outside of Xcode, as its own app--unless I edit the Lua build settings as I mentioned above

**Comment by sbarex** [comment]
try now to reclone the project

**Comment by rileytwo** [comment]
it worked! what did you change?

**Comment by rileytwo** [comment]
Scratch that--it's not running now, unless I turn tick the debug box.

**Comment by rileytwo** [comment]
It looks like it's somewhere in this block:

```zsh
debug "# generating the preview…"
    if [ "${thumb}" = "1" ]; then
        ${reader} | head -n 100 | head -c 20000 | "${cmd}" ${cmdOpts} 2>> ${err_device} && exit 0
    elif [ -n "${maxFileSize}" ]; then
        ${reader} | head -c ${maxFileSize} | "${cmd}" -T "${target}" ${cmdOpts} 2>> ${err_device} && exit 0
    else
        ${reader} | "${cmd}" -T "${target}" ${cmdOpts} 2>> ${err_device} && exit 0
    fi
```

Specifically the redirections with `2>> ${err_device}`. `${err_device}` is only set if `debug` is turned on, so any errors are being redirected to a variable that isn't set (`${err_device}`).

I was able to get it to run by removing the redirects

**Comment by sbarex** [comment]
> it worked! what did you change?

I dont' know 😄 I have removed and readded the submodule…

**Comment by sbarex** [comment]
> Scratch that--it's not running now, unless I turn tick the debug box.
> 
> I think `colorize.sh` is the cause... let me look

Yes it's true I didn't realize it!
I made a typo in the name of the stderr (is /dev/stderr and not /std/stderr!).
