### ISSUE TITLE
disable for binary files

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#122]
It's trying to read binary files as plain text. I want to disable this completely
<img width="1298" alt="Ekran Resmi 2021-11-19 00 02 17" src="https://user-images.githubusercontent.com/36481442/142496426-db6ac506-5ee6-4493-b0bf-59121ff82d36.png">

# or "dump data files" checked

<img width="1298" alt="Ekran Resmi 2021-11-19 00 01 32" src="https://user-images.githubusercontent.com/36481442/142496491-f07ec6f3-0b47-4e6f-a137-d937d2edb12b.png">

**Comment by sbarex** [comment]
The dump output with the html engine is fixed on release 2.1.2.

**Comment by hazarek** [comment]
> The dump output with the html engine is fixed on release 2.1.2.

2.1.2 same.
I mean. I want the default macOS view. like this.

<img width="621" alt="Ekran Resmi 2021-11-19 21 10 58" src="https://user-images.githubusercontent.com/36481442/142671250-6a25bc8d-86bf-4f6a-ba1e-08db3e4c7a1c.png">

Why does the application take ownership of binary executables?

**Comment by sbarex** [comment]
The application handle `public.executable` and `public.unix-executable` UTIs because executable files are often plain shell scripts.

With the release 2.1.3, il you disable the dump option, the binary files are show with the default macOS preview (only on macOS 12 Monterey).

**Comment by hazarek** [comment]
Thanks
