### ISSUE TITLE
[BUG] Main app could not start on M1 Pro

### ISSUE THREAD

**Issue by gmcinalli** [sbarex/SourceCodeSyntaxHighlight#124]
![Schermata 2021-11-23 alle 16 19 07](https://user-images.githubusercontent.com/9024983/143052953-c49d9b94-cb25-41c4-bca8-2ab94b7c91a0.png)

Report: https://pastebin.com/4z7ztvkq.

**Comment by gmcinalli** [comment]
I'm on a fresh install, this Mac is new, I had the error from the first start of the app, right after installing it.

**Comment by sbarex** [comment]
I think I have found the bug, I will release the new version very soon.

The new processor appears to be (rightfully) stricter with memory pointers.

**Comment by gmcinalli** [comment]
Thank you!


Il 23 nov 2021, 16:58 +0100, sbarex ***@***.***>, ha scritto:

**Comment by sbarex** [comment]
Try the release 2.1.3 (50).

**Comment by gmcinalli** [comment]
It works! Thanks @sbarex.
