### ISSUE TITLE
.ts not support

### ISSUE THREAD

**Issue by shang1219178163** [sbarex/SourceCodeSyntaxHighlight#127]
this is a pefect app! but

.
![Image_20211201153756](https://user-images.githubusercontent.com/3699729/144191780-fc59ab77-7631-4032-b4f9-68fb8e5506bf.png)
<img width="579" alt="Image_20211201150733" src="https://user-images.githubusercontent.com/3699729/144191793-809a781e-7b91-45e0-9426-c580021a4242.png">

**Comment by sbarex** [comment]
MacOS associates the `.ts` extension to the mpeg stream video format. Unfortunately Apple does not allow you to customize the preview of some common formats including the video ones. As a result my application, even though it may preview `.ts` formats, is not actually used.

**Comment by guillemap** [comment]
Any chance to get it working like QLColorCode?
https://gregbrown.co/code/typescript-quicklook

I prefer your extension as it seems more up to date :)

**Comment by sbarex** [comment]
There is currently no way to handle the `.ts` format which is reserved by the operating system. I don't know of any software that can do this. The `.tsx` extension, on the other hand, is supported.
