### ISSUE TITLE
Add support for PDDL files

### ISSUE THREAD

**Issue by hectorpal** [sbarex/SourceCodeSyntaxHighlight#128]
Could please add PDDL as an extension for highlight.
As starter, please use **Lisp** highlight. Otherwise, the VSCode extension has many details on syntax.
https://github.com/jan-dolejsi/vscode-pddl

This is probably useful:
```
> mdls -name kMDItemContentType -name kMDItemContentTypeTree  problem01.pddl 
kMDItemContentType     = "dyn.ah62d4rv4ge81a3deru"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge81a3deru",
    "public.data"
)
```

# Why?

PDDL is language for describing planning domains used by automated planners.
See some examples here:
https://github.com/aibasel/downward-benchmarks
We have been using the same format for over 20 years, and continue using it today.
https://www.icaps-conference.org/competitions/

We are improving the tooling. For instance, now we have a VSCode extension
https://marketplace.visualstudio.com/items?itemName=jan-dolejsi.pddl

Thank you!

**Comment by sbarex** [comment]
I'm not the develeloper of the highlight engine. 
You have to ask [André Simon](https://gitlab.com/saalen/highlight/) to support a new language.

For now, with the release 2.1.4, `pddl` files are handled with the `lisp` format.
