### ISSUE TITLE
Add support for OPML files

### ISSUE THREAD

**Issue by kamusis** [sbarex/SourceCodeSyntaxHighlight#129]
❯ mdls -name kMDItemContentType -name kMDItemContentTypeTree  Pg_RSS.opml
kMDItemContentType     = "public.data.xml.opml"
kMDItemContentTypeTree = (
    "public.data.xml.opml",
    "public.data",
    "public.item",
    "public.xml",
    "public.text",
    "public.content"
)

I used "Inquiry format" for OPML files, the result shows "Supported and handled", but quick look can't show anything even after installing this extension.

**Comment by sbarex** [comment]
Try the new release 2.1.4.

**Comment by kamusis** [comment]
Gosh! you are so quick! It works on 2.1.4.
