### ISSUE TITLE
doesn't work with gatekeeper 

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#13]
i am getting `"Syntax Highlight.app" is damaged and can’t be opened. You should move it to the Trash` warning. 
`App Store and identified developers.` is cheked

Is the app notarized?

version https://github.com/sbarex/SourceCodeSyntaxHighlight/releases/tag/1.0b10
macos catalina 10.15.1

**Comment by sbarex** [comment]
No, the app is not signed and not even notarised.
I reuploaded the app
