### ISSUE TITLE
Request to add support for .command files

### ISSUE THREAD

**Issue by Joolyan** [sbarex/SourceCodeSyntaxHighlight#130]
After experiencing difficulties with some QuickLook plugins in Big Sur, your application 'Syntax Highlight' worked perfectly - helped by an excellent Readme.md

"If you found an unhandled format please send me the output of above command."

mdls -name kMDItemContentType -name kMDItemContentTypeTree ~/Support/Scripts/pptx2utf.command
kMDItemContentType     = "com.apple.terminal.shell-script"
kMDItemContentTypeTree = (
    "com.apple.terminal.shell-script",
    "public.script",
    "public.source-code",
    "com.apple.terminal.shell-script",
    "public.data",
    "public.plain-text",
    "public.shell-script",
    "public.item",
    "public.content",
    "public.text"

As .sh kMDItemContentType "public.shell-script" is supported, may be it's possible to add support for .command files?

Thanks again. Great work!

**Comment by sbarex** [comment]
Try the new release 2.1.5 (52).

**Comment by Joolyan** [comment]
Wow! A quick fix and an easy update process.

Updated, tested and confirmed. Many thanks.
