### ISSUE TITLE
JSON preview seems to break on parsing errors

### ISSUE THREAD

**Issue by mreichelt** [sbarex/SourceCodeSyntaxHighlight#131]
First of all: Thank you for this great project!

It seems the JSON preview only works with valid JSON - maybe because it'a run through a prettifier first, and that seems to fail. In that cases I would it expect to just show the unprettified JSON.

Example: given the following content:

```json
{
  "some": "json",
  "foo": 42,
}
```

The preview will look like this:

<img alt="not showing json preview" src="https://user-images.githubusercontent.com/400322/145580006-f4438749-0b8d-45f0-b245-c1a3f0600c75.png" width="300">

When I remove the error comma like this it will render fine:

```json
{
  "some": "json",
  "foo": 42
}
```

<img alt="valid json works" src="https://user-images.githubusercontent.com/400322/145580278-8012d0b2-0037-45f5-b06d-b117152f3d96.png" width="300">

**Comment by sbarex** [comment]
Json files are beautified with python that required a strict valid json file. 

To disabe this features you must edit the json settings, replacing the preprocessor value with a space:
<img width="631" alt="Schermata 2021-12-10 alle 15 37 24" src="https://user-images.githubusercontent.com/1948940/145590966-b2dffba4-a7ca-4f56-b5f5-723fcdc23edc.png">
.

**Comment by mreichelt** [comment]
That works for me, thanks. The file can then be highlighted:
![image](https://user-images.githubusercontent.com/400322/145595192-5572b824-0220-4f54-a974-bfde5e4100a2.png)

What do you think about making this the default for all users?
