### ISSUE TITLE
Support for .readme files?

### ISSUE THREAD

**Issue by Joolyan** [sbarex/SourceCodeSyntaxHighlight#133]
Is it possible to add support for .readme files, formatted as plain text?

kMDItemContentType     = "dyn.ah62d4rv4ge81e3pbqv00n"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge81e3pbqv00n",
    "public.data"
)

**Comment by sbarex** [comment]
Implemented on release 2.1.6.
