### ISSUE TITLE
.txt file preview not working on macOS Monterey

### ISSUE THREAD

**Issue by ph0ngp** [sbarex/SourceCodeSyntaxHighlight#139]
The app is working great with all other supported file types, but when I preview `.txt` or `.text` files, I still see the native Quick Look interface popping up. I am using macOS Monterey 12.1

**Comment by sbarex** [comment]
I think Apple has added the `.txt` format among those that cannot be handled.

**Comment by StanleyCruvinel** [comment]
Hi Syntax Highlight is best!  Thanks so much.

How can'I fix ?

```
$ mdls -name kMDItemContentType -name kMDItemContentTypeTree test.txt
kMDItemContentType     = "public.plain-text"
kMDItemContentTypeTree = (
    "public.plain-text",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)
```

**Comment by sbarex** [comment]
Unfortunately, nothing can be done. The application is already configured to manage the `public.plain-text` format. But the operating system does not allow you to customize the preview of `.txt` files.

**Comment by StanleyCruvinel** [comment]
thanks for the answer. 
Maybe in the next MacOS update apple allow that. 
👍  @sbarex

**Comment by bvandergiessen** [comment]
Ah, that explains it, thanks. I was trying all kinds of tricks to get it right, but it's simply impossible.
Perhaps you could update the Readme.md, section "File format management".
