### ISSUE TITLE
Support .srt subtitle files

### ISSUE THREAD

**Issue by Calvin-Xu** [sbarex/SourceCodeSyntaxHighlight#141]
This is the most common subtitle file format, and it would be amazing if it could be supported.

**Comment by sbarex** [comment]
Sorry but is not a format supported by the formatting engine.
It is also not very relevant to programming languages.

**Comment by Calvin-Xu** [comment]
I see. Would it be possible to configure the app to display it as plaintext?

**Comment by hazarek** [comment]
@Calvin-Xu https://github.com/tattali/QLAddict

**Comment by Calvin-Xu** [comment]
> @Calvin-Xu https://github.com/tattali/QLAddict

Thank you. But does it work for you on 12.1? It does not work on my system. In any case I'll close this issue soon.
