### ISSUE TITLE
Support for Markdown file?

### ISSUE THREAD

**Issue by minh-trancong** [sbarex/SourceCodeSyntaxHighlight#143]
Hello, 
Thank you for a wonderful app! It helps me a lot for viewing code without opening files.
I have a suggestion. Do you have any plans for supporting `.md` files? I think it will be great to see markdown files with Quick Look, especially when looking at README.md files locally.

**Comment by ShengChangYang** [comment]
@minh-trancong 
Already has an app!!
https://github.com/sbarex/QLMarkdown

**Comment by minh-trancong** [comment]
Thank you very much 🤩

**Comment by cukabeka** [comment]
I saw that there's this other app, but I'd love to see this handled by SourceCodeSyntaxHighlight, too! 

I don't exactly need the complete Rendering, just colors and bold/italic would do, and it would spare me another app to be installed.

**Comment by sbarex** [comment]
No, I won't be restoring Markdown support in this app. Almost all people want to see the formatted file, not its source code.
For this, you can use my other program [QLMarkdown](https://github.com/sbarex/QLMarkdown), which can be set to display the source code instead of the formatted one.

**Comment by Atcold** [comment]
Coming here for the same issue. Can we point out, within the app, that there's another app for these files? Currently, it seems like a bug not supporting a specific file format.

**Comment by sbarex** [comment]
Unfortunately, it is not possible to prioritize between different Quick Look preview generators. Therefore, it may happen that another app takes over the management of some of the formats supported by this one.

**Comment by Atcold** [comment]
Maybe I wasn't clear.

*SourceCodeSyntaxHighlight* currently doesn't highlight markdown files. This seems an obvious bug.
The reason is that there is *another* utility that *renders* these files.
The user doesn't know this and face the obvious lack of syntax highlighting as a bug.
Now, if the user understands they need *QLMarkdown*, then they can fix this issue.

Still, I don't understand why the syntax highlighting is disabled for markdown files.

**Comment by sbarex** [comment]
The markdown format is intentionally not supported and will not be in the future. Most users don't want to see the syntax of an .md file, but rather its formatting. For this reason, I've developed a [dedicated application](https://github.com/sbarex/QLMarkdown) that can also display only the highlighted syntax.

**Comment by Atcold** [comment]
Did you read my message?
This is a bug.
Like if VS Code would not syntax highlight MD files because you can render them…

If a user doesn’t want syntax highlighting, then they could choose an option to disable it for specific types.

**Comment by kishan-dhankecha** [comment]
@sbarex I get the point you made.

Although there are people who don't want to see formatted Markdown and only need to see contents of the file but with syntax highlighting.

The solution:

We already have the settings override at the file type level, so there is possibility to add markdown file support and allow user to decide if they want to format it or just syntax highlight the source.

**Comment by batuozdemir** [comment]
I don't understand why you intentionally withdraw support for markdown highlighting. I frequently copy paste markdown snippets from quicklook, so why do I have to install QLMarkdown for something this app is perfectly capable of doing? I just want to access the raw .md text, with syntax highlighting.
