### ISSUE TITLE
Option to disable ligatures

### ISSUE THREAD

**Issue by archetyped** [sbarex/SourceCodeSyntaxHighlight#144]
Hi, how can we disable usage of ligatures in the quicklook preview?

For example, I would like to use a front that supports ligatures (e.g. Fira Code), but do not want ligatures to be displayed as they are less distinct at a glance (e.g. ligatures for `==` and `===`, etc.).

Thank you.

**Comment by sbarex** [comment]
I haven't tested it but try these general settings: 
- render engine: html (not suggested before monterey)
- custom css style: customize with a code like this:
```css
* {
font-variant-ligatures: none;
}
```

**Comment by sbarex** [comment]
Fixed the css bug on release 2.1.7.

**Comment by archetyped** [comment]
Thanks!
