### ISSUE TITLE
Install of command line tool: missing protection of white space in (two) path names in the dialog text

### ISSUE THREAD

**Issue by balanco** [sbarex/SourceCodeSyntaxHighlight#147]
As of version 2.1.8 (56),
selecting the entry "Install the command line tool" from the "Syntax Highlight" menu brings up a dialog stating:

> …
> You can call the tool directly from this path: 
> `/Applications/Syntax Highlight.app/Contents/Resources/syntax_highlight_cli`
> 
> Manually install from a Terminal shell with this command: 
> ln -sfv `/Applications/Syntax Highlight.app/Contents/Resources/syntax_highlight_cli` /usr/local/bin/syntax_highlight_cli

The issue is that in neither of the two occurrences of the app's "syntax_highlight_cli" binary (highlighted in the above quote),…
- neither the blank in  `…/Syntax Highlight.app/…` (which is always there);
- nor any _additional_ whitespace that may be contained in the path name of some non-standard location where the app has been installed,

…are properly protected or escaped.

For example, all occurrences of the path name could be wrapped in single quotes, `'`…`'`, e.g.:
>  …
> You can call the tool directly from this path: 
> `'`/Non standard installation path/with [?*] {strange, characters}/Syntax Highlight.app/Contents/Resources/syntax_highlight_cli`'`
> 
> Manually install from a Terminal shell with this command: 
> ln -sfv `'`/Non standard installation path/with [?*] {strange, characters}/Syntax Highlight.app/Contents/Resources/syntax_highlight_cli`'` /usr/local/bin/syntax_highlight_cli

With many thanks for this _useful_ tool!

**Comment by sbarex** [comment]
Thanks! The space in the name has created a lot of problems for me.

**Comment by sbarex** [comment]
Fixed on release 2.1.9.
