### ISSUE TITLE
mime detection on plain files not working

### ISSUE THREAD

**Issue by stefanwascoding** [sbarex/SourceCodeSyntaxHighlight#148]
According to the docs:

> Unknown files are analyzed with the system utility `/usr/bin/file` for recognize mime type and encoding.

However this seems to not be working as (I) expected.  I have quite a few files without extensions that are Bash, Perl, or Python scripts, that do not get any syntax highlighting, they are just displayed as normal text with line numbers.  The result of `/usr/bin/file --mime --brief` on them is: `text/x-shellscript`, `text/x-perl`, and `text/x-script.python` respectively (charset is always `charset=us-ascii`).

If I specifically add them to the "Text files" list with their file name pattern and force the syntax, they show up highlighted as expected.

macOS 12.2.1
Syntax Highlight 2.1.8

**Comment by sbarex** [comment]
The problem is in the conversion from mime type to UTI. Even if the mime type is associated with a system UTI, macOS generates a dynamic UTI that is not recognized by the app.
In version 2.1.9 I added the option to set a new criteria for the mime type in the settings for plain files.

**Comment by stefanwascoding** [comment]
Works for me!  Thank you. 🙇🏻
