### ISSUE TITLE
Color Slider Causes Lag

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#149]
Color slider causes lag

https://user-images.githubusercontent.com/36481442/156594830-532aa996-3270-4b96-9e67-c4096a3bd435.mp4

**Comment by sbarex** [comment]
No easy fix. When you change the color, the preview will be updated. The color slider generates a continuous update every time it is dragged.

**Comment by hazarek** [comment]
> No easy fix. When you change the color, the preview will be updated. The color slider generates a continuous update every time it is dragged.

problem is solved if colors are applied only when the cursor is released. No need for real-time color change.

**Comment by sbarex** [comment]
Fixed on release 2.1.10 (58).
