### ISSUE TITLE
Support Pretty Printing JSON

### ISSUE THREAD

**Issue by alexclst** [sbarex/SourceCodeSyntaxHighlight#15]
Not all JSON files are saved with their content pretty printed. It’d be great if you could pretty print the content of JSON files before displaying them.

As an alternative to updating the app itself for this, does anyone know if there is a way to tell `highlight` to run a separate command on the input itself? I’ve looked at its docs and not found anything I find suitable, but may well be missing or misreading something. If there is such a thing I’d rather set up additional flags on the command when previewing JSON files that uses something like `python -m json.tool` to do the pretty printing anyway over the app doing something custom for JSON files.

**Comment by sbarex** [comment]
Highlight don't have any pretty print functions.
But colorize.sh use a sort di preprocessor to handle some file type (for example .class files are decompiled before processed by highlight).
So in the next release there is a new gui element to specify a custom preprocessor usable also to pretty print the code.

**Comment by alexclst** [comment]
Awesome, thanks. I’ll look for it when the update comes out.

**Comment by sbarex** [comment]
Ok, try the release 1.0.b12.

**Comment by dantechguy** [comment]
Hi, I'm wondering how to enable the pretty printing? Even after enabling the advanced settings I can't find any UI element about a custom preprocessor (haven't a clue what that means either).

Any help on this would be greatly appreciated.

**Comment by iandundas** [comment]
<img width="3126" height="1888" alt="Image" src="https://github.com/user-attachments/assets/faec1dde-7889-41e2-ab7f-ff95255bbd47" />

this worked for me using `jq`
