### ISSUE TITLE
Support for mobileconfig files

### ISSUE THREAD

**Issue by flammable** [sbarex/SourceCodeSyntaxHighlight#150]
Thanks for this app! It's really fantastic, and makes my life much easier. I really appreciate it!

I work with configuration profiles a lot. Would it be possible to support these, too? They're XML files (possibly plist files) with a .mobileconfig file extension, and this app already supports both file types.

```
% mdls -name kMDItemContentType -name kMDItemContentTypeTree Firefox.mobileconfig
kMDItemContentType     = "com.apple.mobileconfig"
kMDItemContentTypeTree = (
    "com.apple.mobileconfig",
    "public.xml",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)
```

If you'd like to see an example, I have a few in [this GitHub repo](https://github.com/flammable/profiles). Thanks again!

**Comment by sbarex** [comment]
Implemented on release 2.1.0 (58).
