### ISSUE TITLE
2.1.10 (59) triggered CleamMyMac adware detection

### ISSUE THREAD

**Issue by i0ntempest** [sbarex/SourceCodeSyntaxHighlight#155]
Most likely a false positive but just would like you to know. Build 58 was fine.
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/16017904/157948347-9cc6b05b-52de-4934-af0c-658499ca88fa.png">

**Comment by sbarex** [comment]
strange, in my system it is not detected

**Comment by i0ntempest** [comment]
Yea it is weird, it only triggered realtime monitor once when installing this version, but later manual scans will not pick it up.

**Comment by i0ntempest** [comment]
Never triggered again after that first trigger, could be some sort of glitch in CleanMyMac. Closing for now
