### ISSUE TITLE
How to add support for ssh '.pub' key files?

### ISSUE THREAD

**Issue by dppeak** [sbarex/SourceCodeSyntaxHighlight#158]
How can we get support for .pub files?  These are just plain text files.

Here's the result from Inquiry file.

<img width="633" alt="Screen Shot 2022-03-14 at 10 47 36 AM" src="https://user-images.githubusercontent.com/868044/158209289-4e037374-37e9-4bc8-8415-b3681f0d230f.png">

**Comment by sbarex** [comment]
What programming language does the .pub extension use?

**Comment by dppeak** [comment]
They are plain text files, so no syntax highlighting.

**Comment by zhanggang807** [comment]
watch this issue

**Comment by sbarex** [comment]
Implemented on release 2.1.15 (64).
