### ISSUE TITLE
Open with double click doesn't work.

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#16]
hello I came again:) the latest update has been perfect.
1. Double-clicking the quicklook window does not open the file.
2. theme search  is case sensitive, search should be case insensitive. "base" and "Base" gives different results.
<img width="398" alt="cap" src="https://user-images.githubusercontent.com/36481442/69055874-e0ccbf00-0a1f-11ea-9a61-88aba80db5e6.png">

**Comment by hazarek** [comment]
This problem is still present; "Resetting font when application is reopened."

**Comment by sbarex** [comment]
ok, I will fix the search bug in the next release.
For the double click I have to study how to do it.

Now I'm develop a theme gui interface…

**Comment by hazarek** [comment]
@sbarex what about "Resetting font when application is reopened."

**Comment by sbarex** [comment]
> @sbarex what about "Resetting font when application is reopened."

even that bug will be corrected, sorry

**Comment by sbarex** [comment]
Solved in release 13
