### ISSUE TITLE
quicklook does not work on some symbolic links

### ISSUE THREAD

**Issue by vpicouet** [sbarex/SourceCodeSyntaxHighlight#165]
Hello I use the last vesion of SourceCodeSyntaxHighlight and I do not manage have a quicklook of a symbolic link of .bashrc
Quicklook of the original file work fine.
Is there a way to bypass this issue?
Thanks for this great app!

![Capture d’écran, le 2022-04-22 à 11 03 03](https://user-images.githubusercontent.com/37241971/164741461-9f71b85e-25fa-4b6e-b13e-c0e5a5ccfea9.jpg)

**Comment by sbarex** [comment]
Strange, it works for me.

Does the problem occur with macos aliases (created with the Finder) or symbolic links created by the terminal?
Obviously the link is valid and points to an existing and readable file?

Can I see the output of `ls -l` in the folder containing the alias?

**Comment by vpicouet** [comment]
Sorry, you are right, the link was broken and was not associated to the file anymore. Thanks for the answer!
