### ISSUE TITLE
Issues with settings for plain files

### ISSUE THREAD

**Issue by jpcirrus** [sbarex/SourceCodeSyntaxHighlight#166]
Syntax Highlight version 2.1.11 (60) running on macOS 12.3.1 on an M1 Mac.

1. When configuring a hidden file in the "Settings for plain files" tab of Preferences to get syntax highlighting to display in Quick Look, the setting "Use regular expression" needs to be enabled (and the leading dot in the file name escaped). If not, the file is displayed in Quick Look but with no syntax highlighting.
<img width="571" alt="syntax-highlight-settings" src="https://user-images.githubusercontent.com/39587/165043052-e198e2ee-cef5-4960-b220-58f394ec7ed6.png">

2. And, such a file, despite displaying the configured syntax highlighting in Quick Look, does not display the VCS information. For example, Sublime Text indicates 1 addition and 1 change to this file,
<img width="426" alt="vcs-sublime-text" src="https://user-images.githubusercontent.com/39587/165043780-e87b7eae-b905-4457-bdd3-01506ad01d64.png">
but no VCS information is shown in Quick Look.
<img width="437" alt="vcs-quick-look" src="https://user-images.githubusercontent.com/39587/165043916-c9d92540-e0d0-418f-8c62-6bb9c6239733.png">
But VCS information is displayed corretly for files that are not added to "Settings for plain files".

**Comment by sbarex** [comment]
Sorry, the right command is:

``sh
cd DRAG_here_the_FOLDER_of_the_file
git diff -U0 -0 DRAG_here_the_FILE
``

**Comment by sbarex** [comment]
try this preliminary version, it should fix the other vcs color bug as well.
[Syntax Highlight.zip](https://github.com/sbarex/SourceCodeSyntaxHighlight/files/8556759/Syntax.Highlight.zip)

**Comment by jpcirrus** [comment]
I confirm that this preliminary version fixes these 2 issues as well as #167. Many thanks.

**Comment by sbarex** [comment]
Fixed on release 2.1.12 (61). Please redownload the last release for the others bugfix.
