### ISSUE TITLE
Custom VCS colors are not persisted

### ISSUE THREAD

**Issue by jpcirrus** [sbarex/SourceCodeSyntaxHighlight#167]
Syntax Highlight version 2.1.11 (60) running on macOS 12.3.1 on an M1 Mac.

When custom colors are configured and saved in Preferences -> General -> VCS Support, Customize, they are not persisted between restarts of the Syntax Highlight application. They revert to the default colors.

**Comment by sbarex** [comment]
Fixed on release 2.1.12 (61).
