### ISSUE TITLE
Do not manage to build with Xcode

### ISSUE THREAD

**Issue by vpicouet** [sbarex/SourceCodeSyntaxHighlight#17]
Hello,
Thanks for this work!
I did not manage to build the app.
Best

Vincent

![Capture d’écran, le 2019-11-18 à 17 00 05](https://user-images.githubusercontent.com/37241971/69068350-e11b8900-0a24-11ea-94d8-6cbf6a0301a6.jpg)

**Comment by sbarex** [comment]
Without seeing the error list it is impossible to help you.
the precompiled version is downloaded from here:

<img width="1041" alt="Schermata 2019-11-18 alle 17 05 32" src="https://user-images.githubusercontent.com/1948940/69068872-d44b6500-0a25-11ea-8a44-37bd1d2761a2.png">

**Comment by vpicouet** [comment]
Thanks, just found it (sorry about it).
Here is the error.
Working with the pre-compiled for now.

![Capture d’écran, le 2019-11-18 à 17 08 18](https://user-images.githubusercontent.com/37241971/69069025-1379b600-0a26-11ea-9d08-f1246c645ec5.jpg)

**Comment by sbarex** [comment]
I believe there is some error in the configuration of your xcode. It seems strange to me that the path of inclusion uses /Library/Developer/CommandLineTools/…
Foundation is a system framework. It is impossible for xcode to try to compile it.
Check your xcode installation and configuration (especially the preferences locations panel).

**Comment by vpicouet** [comment]
Ok, thanks.
Do you know if there is a way to have a preview on other text files that end with an other extension than .txt for instance:
.in, .para, .out, .log, ,error? I had a quicklook extension that used to do this but it doesn't working anymore on Catalina.
One example for the .para:

Vincent$ mdls -name kMDItemContentType -name kMDItemContentTypeTree /Users/Vincent/Nextcloud/Work/LePhare/param/output_lf.para 
kMDItemContentType     = "dyn.ah62d4rv4ge81a2pwqe"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge81a2pwqe",
    "public.data"
)

Thanks for your help,

**Comment by sbarex** [comment]
I don't know the .para format.
This application acts as a wrapper for the highlight utility. So it only handles the sorce formats supported by highlight.
From view menu, open `inquiry file format` and drag your file on the window. It is show if the format is supported by highlight.

**Comment by sbarex** [comment]
I hope it's solved in release 13.
