### ISSUE TITLE
Allow dark color scheme when independently of system setting

### ISSUE THREAD

**Issue by DaveAllbirds** [sbarex/SourceCodeSyntaxHighlight#171]
Please consider adding the ability to set the color scheme to `Dark` globally even if users have Appearance set to `Light`.

**Comment by sbarex** [comment]
You can choose a dark theme also for the light appearance 😉

**Comment by DaveAllbirds** [comment]
Ah, so you can. Didn't realize that was an option. Maybe include that in the docs? 😉

<img width="202" alt="CleanShot 2022-04-27 at 10 18 39@2x" src="https://user-images.githubusercontent.com/94491191/165583299-da793de1-3c31-45d1-b581-970dd931862e.png">

**Comment by shineshane** [comment]
> Ah, so you can. Didn't realize that was an option. Maybe include that in the docs? 😉
> 
> <img alt="CleanShot 2022-04-27 at 10 18 39@2x" width="202" src="https://user-images.githubusercontent.com/94491191/165583299-da793de1-3c31-45d1-b581-970dd931862e.png">

Not intuitive, better to add a standalone configuration like this:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/9608276/183609904-11fb29b8-b7b3-4287-9914-9cfa6f1495be.png">
