### ISSUE TITLE
Add .ods file extesion

### ISSUE THREAD

**Issue by reinbeumer** [sbarex/SourceCodeSyntaxHighlight#174]
Hi,

Is it possible to add .ods extension (Libre Office)?

kMDItemContentType     = "org.oasis-open.opendocument.spreadsheet"
kMDItemContentTypeTree = (
    "org.oasis-open.opendocument.spreadsheet",
    "org.oasis-open.opendocument",
    "public.data",
    "public.item",
    "public.composite-content",
    "public.content",
    "public.spreadsheet"
)

**Comment by sbarex** [comment]
Hi, sorry but this Quicklook extension is intended to support only syntax highlighting for files related to programming languages.
