### ISSUE TITLE
Possible to add .jsonc format?

### ISSUE THREAD

**Issue by frypf** [sbarex/SourceCodeSyntaxHighlight#183]
I have a bunch of `.jsonc` files in various projects so was wondering if it would be possible to render these using the same scheme as `.json`? Using the Inquiry Tool gives some weird results for their UTI though, so I've no idea how trivial this would be 🤔

Many thanks for such a useful tool! 
<img width="962" alt="Screenshot 2022-07-05 at 00 19 28" src="https://user-images.githubusercontent.com/65832791/177224726-eecaf633-b14b-48df-a0d2-b459baa93fe6.png">

**Comment by sbarex** [comment]
Implemented on release 2.1.15 (64).
