### ISSUE TITLE
quicklook window settings

### ISSUE THREAD

**Issue by crashmeister** [sbarex/SourceCodeSyntaxHighlight#19]
Please look into saving the size and position of the popup window for the next use.
It's very frustrating to have to resize it every time.

**Comment by sbarex** [comment]
which popup windows are you referring to?

**Comment by crashmeister** [comment]
When you open the quick view by pressing the space bar from Finder.

Craig Horrell
< Nothing is foolproof to a sufficiently talented fool >

**Comment by hazarek** [comment]
macos does not save quicklook window size as default. saving window size is a bad idea. position must save.

**Comment by crashmeister** [comment]
@hazarek I know macOS does not save size/position. It should. @sbarex can do this with his QLGenerator.

Why is size a bad idea ? The default is far too small and it is a frustrating waste of time resizing every time you use it.

**Comment by sbarex** [comment]
on my mac the quickloock window remeber position and size... I do not understand why on your no ... among other things, the extension does not define the window but only is contents.

**Comment by hazarek** [comment]
on my mac the quicklook window only remember position. not size. interesting.
