### ISSUE TITLE
Add Support for .cshtml

### ISSUE THREAD

**Issue by renecum** [sbarex/SourceCodeSyntaxHighlight#195]
It would be very useful for .net core web developers to preview cshtml files with quick look.

```
kMDItemContentType     = "dyn.ah62d4rv4ge80g65ksv002"
kMDItemContentTypeTree = (
    "public.data",
    "public.item",
    "dyn.ah62d4rv4ge80g65ksv002"
)
```

Thanks for your help.

**Comment by sbarex** [comment]
I don't know the syntax of this extension. Should it be formatted as html code or as c# code?

**Comment by renecumcignium** [comment]
For me Html is fine. It allows Razor format, you can see more about it here.

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0
https://learn.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-6.0

Thanks.

**Comment by sbarex** [comment]
Implemented as csharp

**Comment by renecumcignium** [comment]
Thank you very much.
