### ISSUE TITLE
syntax_highlight_cli not working

### ISSUE THREAD

**Issue by serge-ivamov** [sbarex/SourceCodeSyntaxHighlight#204]
```bash
$ "/Applications/Syntax Highlight.app/Contents/Resources/syntax_highlight_cli" /tmp/test.sh
Error processing /tmp/test.sh: Syntax Highlight: colorize.sh failed with exit code 127. Command was ('/Applications/Syntax Highlight.app/Contents/Contents/Resources/highlight/colorize.sh' '/tmp/test.sh').

command: '/Applications/Syntax Highlight.app/Contents/Contents/Resources/highlight/colorize.sh' '/tmp/test.sh'
exitCode: 127
```
/Contents/<del>Contents</del>/Resources/highlight/colorize.sh

**Comment by sbarex** [comment]
Fixed on release 2.1.16.

**Comment by sirlaurie** [comment]
It happened again with 2.1.17. OS: 12.6.2. install from brew with suggest command.

**Comment by sirlaurie** [comment]
I downgrade to 2.1.16, and it happened again. and I found this weird problem: no matter how many time I run `xattr -d com.apple.quarantine`, the colorize.sh file always has a `@` in the `ls -l` result
<img width="433" alt="Screen Shot 2023-01-12 at 13 36 55" src="https://user-images.githubusercontent.com/8928155/211986437-0e03a944-db34-431f-ab94-4ff03520544e.png">

so, how to solve this?

**Comment by sbarex** [comment]
Try with `ls -l@ ` the see all the extended attributes.

Use the `xattr -cr filename.ext` tro strip all extended attrs.

**Comment by W-quan** [comment]
version: 2.1.21(70) reoccur.
