### ISSUE TITLE
what is the compressed files ql in your readme snapshot?

### ISSUE THREAD

**Issue by mooonfly** [sbarex/SourceCodeSyntaxHighlight#205]
i want to know what is the compressed files ql, please tell me, thank you

**Comment by sbarex** [comment]
Can you explain the question to me better?

**Comment by hazarek** [comment]
![extensions](https://user-images.githubusercontent.com/36481442/201407459-f7df8073-b24a-4c10-a0bd-7c032595a38f.png)

**Comment by sbarex** [comment]
Ah, is another my app to view compressed files.

**Comment by mooonfly** [comment]
what's the app name？

**Comment by hazarek** [comment]
> Currently the app only lives on my mac ;-)
😞

**Comment by Liuzhj** [comment]
Need "compressed file QL" too, thank you very much.

**Comment by setanarut** [comment]
> Need "compressed file QL" too, thank you very much.

https://macitbetter.com/BetterZip-Quick-Look-Generator/
