### ISSUE TITLE
Add support for .srt

### ISSUE THREAD

**Issue by gustavohellwig** [sbarex/SourceCodeSyntaxHighlight#208]
kMDItemContentType                 = "dyn.ah62d4rv4ge81g6xy"
kMDItemContentTypeTree             = (
    "public.item",
    "dyn.ah62d4rv4ge81g6xy",
    "public.data"
)
...
kMDItemKind                        = "Subrip Subtitle File"

Thank you !!!!

**Comment by hazarek** [comment]
There is another quick view plugin for srt but it is not working and needs to be fixed.

https://github.com/tattali/QLAddict/issues/17#issuecomment-817177030

**Comment by gustavohellwig** [comment]
yes, but is not working as you said.

**Comment by sbarex** [comment]
This format is not supported by the rendering engine.
