### ISSUE TITLE
Having the char " \' " in the folder name results in showing blank preview page 

### ISSUE THREAD

**Issue by rmansour** [sbarex/SourceCodeSyntaxHighlight#210]
Hey there!
Great work on the extension, really really helpful! 

I've noticed a problem whilst trying to preview a file that was in a folder with the character " \' " in its name: I get a blank preview page. For example:

![CleanShot 2022-12-05 at 16 05 54@2x](https://user-images.githubusercontent.com/16895972/205656517-2282484f-0461-4fc6-8f58-7b64192129e7.png)

Removing the character fixes the problem and previews the files correctly.

A fix for that would be greatly appreciated!

**Comment by sbarex** [comment]
Fixed on release 2.1.18.
