### ISSUE TITLE
macOS Ventura: no option to enable Quick Look extension in System Settings

### ISSUE THREAD

**Issue by tsouchlarakis** [sbarex/SourceCodeSyntaxHighlight#216]
In the new System Settings in macOS Ventura, I'm not seeing the analogous option as what's shown in the screenshot for an earlier version of macOS in the README [here](https://github.com/sbarex/SourceCodeSyntaxHighlight#enable-the-quick-look-extension).

Here's what System Settings looks like on Ventura. I've checked all the submenus, and am not able to find Syntax Highlight after installing with brew cask.

<img width="827" alt="Screenshot 2022-12-25 at 12 39 23 PM" src="https://user-images.githubusercontent.com/26070649/209481413-67d62ef4-d27c-4500-b7f9-4bae418f0395.png">

**Comment by sbarex** [comment]
Try to launch the app to force the System to detect the extension, the retry on the System Settings.

On my mac this is the screenshot:
<img width="827" alt="Screenshot 2022-12-25 at 21 46 16" src="https://user-images.githubusercontent.com/1948940/209481578-5adc808a-e42b-4b87-8cac-3d95ce8768ff.png">

**Comment by tsouchlarakis** [comment]
Tried restarting after the install and launching **Syntax Highlight.app**, but nothing seems to happen. I also don't see the **Quick Look** submenu under "Extensions" that you do.

What should happen when you launch the **Syntax Highlight** app?

**Comment by sbarex** [comment]
When you launch the app the system can detect the quicklook extension. Otherwise move the app to the trash and back to the Applications folder.

**Comment by tsouchlarakis** [comment]
Got it. macOS was preventing the app to be opened:

<img width="372" alt="Screenshot 2022-12-27 at 12 23 55 AM" src="https://user-images.githubusercontent.com/26070649/209636695-e8385154-96ab-4e05-be49-09aea829fcd6.png">

and I had to force it it to open in System Settings > Security > Open anyway
