### ISSUE TITLE
truncated theme names

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#22]
unreadable, truncated theme names;
<img width="394" alt="cap" src="https://user-images.githubusercontent.com/36481442/69548892-46cdbf00-0fa9-11ea-9d25-b194a69f9d06.png">

additional;
- qlmarkdown is gone with latest update. Will it come back?

**Comment by hazarek** [comment]
I'll open the issues separately. so you can add it to the 'milestones' page.

**Comment by sbarex** [comment]
Ok, fixed in next release.
Markdown bug also, sorry.
