### ISSUE TITLE
Pointer icon bug

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#23]
the wrong cursor icon appears on first launch.

![69549488-73360b00-0faa-11ea-8338-7c5569c3ca6b](https://user-images.githubusercontent.com/36481442/69550501-281cf780-0fac-11ea-95bc-d54d9eb3ab0d.gif)

**Comment by sbarex** [comment]
Try the 1.0.b15(pre) release. 
On my system the cursor is not wrong but there was still a bug in the style sheet...

**Comment by hazarek** [comment]
pointer bug did not improve. When I wait a few seconds and press the space key again, the wrong icon appears. If I open and close quickly does not appear.
new bugs;

i set word wrap to 110,  there is a horizontal scroll bar.
<img width="811" alt="cap" src="https://user-images.githubusercontent.com/36481442/69557743-2bb67b80-0fb8-11ea-9398-54442695c5eb.png">

I can't hold the corners;
<img width="70" alt="cap 1" src="https://user-images.githubusercontent.com/36481442/69557843-4daffe00-0fb8-11ea-9465-5ee7c98eacb0.png">

**Comment by sbarex** [comment]
You cannot resize the window o cannot drag?
For enable the click and drag window I used a not very elegant solution... for which the click and drag does not work near the right and bottom edge (even if there are no scroll bars)

**Comment by hazarek** [comment]
i can drag but very hard;
![a](https://user-images.githubusercontent.com/36481442/69558702-ba77c800-0fb9-11ea-941c-fb9dc251136b.gif)

**Comment by sbarex** [comment]
From release 1.0.b15(pre) try to download and test [source.highlight2](https://github.com/sbarex/SourceCodeSyntaxHighlight/releases/download/1.0.b15(pre)/Syntax.Highlight.2.zip). It uses a different code to handle window drag. Also test rtf as output format. thanks

**Comment by hazarek** [comment]
sorry no change. The cursor icon changes randomly, and hard to catch. I think you should think from the beginning without hacking the system. The interface has become very complicated and laggy. you care more about themes. nobody uses a syntax-specific theme. no need for theme editor, enough to import commonly used themes. 30mb too much for this kind of plugin. you think like bill gates. Think like Steve Jobs.:)

**Comment by sbarex** [comment]
Patience, the compilation of code is practically only in the interface of preferences, the plugin has not been nearly touched anymore.
Unfortunately, not having my problems on my system, I cannot understand what they are due to.
Of the 30 mb, 11 are occupied by swift libraries, and another 6 by highlight.

**Comment by hazarek** [comment]
Do you have this pointer bug on your system?

**Comment by sbarex** [comment]
No, on my system the window resize normally and no icon bug... for the cursor bug maybe it could depend on processor speed, a faster processor may make this bug less visible. But I don't see it.

**Comment by hazarek** [comment]
SyntaxHighlight windows are different from other windows. The window borders are thinner.
maybe this give you a hint. I can't do anything else.

<img width="806" alt="cap" src="https://user-images.githubusercontent.com/36481442/69584810-2a547580-0fef-11ea-905c-813bee1397c6.png">

txt window
<img width="812" alt="cap 2" src="https://user-images.githubusercontent.com/36481442/69584817-2d4f6600-0fef-11ea-8ee8-33ebada8ade4.png">

**Comment by hazarek** [comment]
I mean, there's no gray line on the inside.
