### ISSUE TITLE
Add support for .jsm filename extension

### ISSUE THREAD

**Issue by JimDanner** [sbarex/SourceCodeSyntaxHighlight#237]
The `.jsm` filename extension is used for [JavaScript Code Modules](https://udn.realityripple.com/docs/Mozilla/JavaScript_code_modules/Using), i.e. the files contain JavaScript source code; `.jsm` is an alternative variation of `.mjs` used by Mozilla applications. I counted 484 `jsm` files in the Firefox source code, and 429 in the Thunderbird source.

Unfortunately, this filename extension is not in Apple's default list for JavaScript files, so the files don't have the `com.netscape.javascript-source` UTI used by Syntax Highlight. They have the dynamic UTI `dyn.ah62d4rv4ge80y65r`. Could this nevertheless be added in, and be parsed by the JavaScript parser?

**Comment by sbarex** [comment]
Implemented on release 2.2.20.
