### ISSUE TITLE
Added support for .mpd (and others)

### ISSUE THREAD

**Issue by piersoh** [sbarex/SourceCodeSyntaxHighlight#238]
It would be useful to add support for [media presentation description (MPD)](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Setting_up_adaptive_streaming_media_sources) files (`.mpd`) which are basically XML files. Here's the output from `mdls`:
```
kMDItemContentType     = "dyn.ah62d4rv4ge8046de"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge8046de",
    "public.data"
)
```
Though when I drop an MPD file on the _Inquiry File_ dialogue in the app it suggests an additional UTI is associated with it:
`dyn.age8046de`

Also It would be nice to have a way - even via the odd command line operations - to add arbitrary files types a bit like is possible for [qlstephen](https://github.com/whomwah/qlstephen/issues/87) by editing its `Info.plist` file.

**Comment by sbarex** [comment]
Implemented on release 2.2.20.

For manual support other formats see the README.md.
