### ISSUE TITLE
Add support for .f95  and .cls file

### ISSUE THREAD

**Issue by okarin001** [sbarex/SourceCodeSyntaxHighlight#239]
Since Fortran and LaTeX are already supported by the app, please add support for `.f95` and `.cls` extensions as well.

## Terminal output

for Fortran f95 file
```
kMDItemContentType     = "public.fortran-95-source"
kMDItemContentTypeTree = (
    "public.fortran-95-source",
    "public.fortran-source",
    "public.source-code",
    "public.plain-text",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)
```
for LaTeX cls file
```
kMDItemContentType     = "org.tug.cls"
kMDItemContentTypeTree = (
    "org.tug.cls",
    "public.text",
    "public.data",
    "public.item",
    "public.content",
    "public.plain-text"
)
```

## Inquiry file in app

<img width="906" alt="image" src="https://github.com/sbarex/SourceCodeSyntaxHighlight/assets/63984668/a228fa7c-1ade-4f26-9ae1-07abae712e24">
<img width="1015" alt="image" src="https://github.com/sbarex/SourceCodeSyntaxHighlight/assets/63984668/a61e8694-575f-4e1e-9fb6-a650666a89c8">

**Comment by sbarex** [comment]
Implemented on release 2.1.19 (68).
