### ISSUE TITLE
when preview a large file, no responding

### ISSUE THREAD

**Issue by loricheung** [sbarex/SourceCodeSyntaxHighlight#24]
I have a json file about 144MB, when highlight the file in finder, it always loading and no responding ever. only with relaunching finder can stop it.

**Comment by sbarex** [comment]
the preview is managed through an html page (or rtf) so with such large files obviously the page requires a large amount of memory to be displayed ... I think I will add an option to limit the amount of data to be highlighted.

**Comment by loricheung** [comment]
thanks
