### ISSUE TITLE
Add support for .smali filename extension

### ISSUE THREAD

**Issue by yingguqing** [sbarex/SourceCodeSyntaxHighlight#252]
Thanks for this great app. It would be great if it supported .smali files which basically are plain-text files.

kMDItemContentType     = "dyn.ah62d4rv4ge81g5pbrvyu"
kMDItemContentTypeTree = (
    "dyn.ah62d4rv4ge81g5pbrvyu",
    "public.item",
    "public.data"
)
Thanks!

**Comment by sbarex** [comment]
Implemented on release 2.2.20.
