### ISSUE TITLE
Add support for .mojo filename extension

### ISSUE THREAD

**Issue by SimplyYummy** [sbarex/SourceCodeSyntaxHighlight#253]
Thanks for this great and awesome app. Can we get `.mojo` and `.🔥` extensions for mojo files supported? 

It isn't currently supported at the moment as its a new language that's a superset of python. Currently there is no preview when using quicklook, which is expected as its a new programming language.

1. Website for mojo language: https://docs.modular.com/mojo/

2. Mojo's official syntax highlighting: https://github.com/modularml/mojo-syntax

3. Converted syntax to tmLanguage if it helps: https://github.com/SimplyYummy/Modular-Mojo-Syntax-Highlighting/blob/main/mojo.syntax.tmLanguage

Running `mdls -name kMDItemContentType -name kMDItemContentTypeTree filename.mojo` shows the below:

```
kMDItemContentType     = "com.coteditor.mojo"
kMDItemContentTypeTree = (
    "com.coteditor.mojo",
    "public.source-code",
    "public.plain-text",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)
```

And the output from `Inquiry` window in Syntax Highlighter.app:

![Screenshot mojo extension](https://github.com/sbarex/SourceCodeSyntaxHighlight/assets/12974299/db17b8ba-bc7f-4d72-8ae4-dfd85a32ceb0)

**Comment by sbarex** [comment]
Sorry, but mojo is not handled by the rendering engine [Highlight](https://gitlab.com/saalen/highlight), that is not compatible with the tmLanguage format.
