### ISSUE TITLE
Not working on Time Machine Backups

### ISSUE THREAD

**Issue by dalalalala** [sbarex/SourceCodeSyntaxHighlight#258]
Hi, Thanks for the great app. The extension works perfect on my machine except a minor issue. When I enter the time machine backup interface, and select a previous version, the quicklook doesn't work: it just displays a blank window. It would be great if you can take a look at this problem, thanks very much.

**Comment by sbarex** [comment]
It could be a system problem. On some special folders the extension seems to fail due to access privileges, for example with files placed in the recycle bin.

**Comment by dalalalala** [comment]
> It could be a system problem. On some special folders the extension seems to fail due to access privileges, for example with files placed in the recycle bin.

Thanks for pointing out the reason. I add the full disk access permission and it works.
