### ISSUE TITLE
Is it possible to provide a prebuilt binary?

### ISSUE THREAD

**Issue by zit-cat** [sbarex/SourceCodeSyntaxHighlight#26]
As titled, I ran into some error about Lua missing and I don't have the bandwidth to look into this right now. I imagine a prebuilt binary would also benefit non-developers, thanks!

**Comment by sbarex** [comment]
yes, the prebuild is on the relases tab:
<img width="1055" alt="Schermata 2020-01-24 alle 08 14 14" src="https://user-images.githubusercontent.com/1948940/73050924-ab11df80-3e81-11ea-8eac-6dbd7541852e.png">
