### ISSUE TITLE
.cmake not present in supported formats.

### ISSUE THREAD

**Issue by Bumblebee00** [sbarex/SourceCodeSyntaxHighlight#262]
<img width="1142" alt="Screenshot 2023-12-16 alle 11 47 17" src="https://github.com/sbarex/SourceCodeSyntaxHighlight/assets/54026028/78b0d261-75c9-4900-ab28-7c1f773e1e09">
I was not able to find cmake in the supported formats in my app (even tough is on the list of supported formats).

Would be cool to add the possibility of adding custom formats, since I would like also matlab (.m) to be supported.

Thanks!

**Comment by sbarex** [comment]
Fixed on release 2.1.21.
