### ISSUE TITLE
[Formats] Add support for assembly (.s, .S)

### ISSUE THREAD

**Issue by parasaito** [sbarex/SourceCodeSyntaxHighlight#263]
Add support for assembly files with `.s` and `.S` extension.

**Comment by sbarex** [comment]
The rendering egine allow to support the _Generic Assembler_ with these extensions: `29k`, `68s`, `68x`, `a51`, `asm`, `x86`. It is valid also for `.s` and `.S`?

**Comment by parasaito** [comment]
@sbarex How do I configure it to be used with `.s` and `.S` files?

**Comment by sbarex** [comment]
You cannot configure additional extensions. You need to recompile the app with the new extension.

**Comment by parasaito** [comment]
> You cannot configure additional extensions. You need to recompile the app with the new extension.

Hence the request. The rendering engine should be able to handle it. All the assembly code I encounter is in `.s` and `.S` extensions, including Linux kernel.

**Comment by sbarex** [comment]
This is why I asked, do files with the extension have the same syntax as those with the 29k, 68s, 68x, a51, asm, x86 extensions?

**Comment by parasaito** [comment]
> This is why I asked, do files with the extension have the same syntax as those with the 29k, 68s, 68x, a51, asm, x86 extensions?

Sorry didn't comprehend the question at first. I thought this project was using highlight.js with a html renderer. 

But only now I learnt it's using some other project called highlight on gitlab. Going through the assembler [source code](https://gitlab.com/saalen/highlight/-/blob/master/langDefs/assembler.lang?ref_type=heads), it might not be able to render arm and riscv instructions. I'll create a pull request in upstream.
