### ISSUE TITLE
Looking for precompiled binary.

### ISSUE THREAD

**Issue by fivetwelve** [sbarex/SourceCodeSyntaxHighlight#27]
The readme makes mention of pre-compiled binaries but I cannot locate it here in the repo nor if there is a website associated for its download.

Could you provide some more information about it or its location? Thank you!

**Comment by sbarex** [comment]
duplicate of #26

**Comment by fivetwelve** [comment]
Cheers for that. I appreciate the work you put into this. 🙏

Might I suggest adding a note about the location (Releases > Assets or Tags > Downloads)  in your Readme?
