### ISSUE TITLE
Terraform files doesn't have syntax highlight

### ISSUE THREAD

**Issue by DanSega1** [sbarex/SourceCodeSyntaxHighlight#272]
On .tf files there are no colors for the text, it's like reading .txt file.

Also it is possible to add option to view .tfstate and
![image](https://github.com/sbarex/SourceCodeSyntaxHighlight/assets/108394291/088e65d0-55ad-465c-b43e-c83278940dd6)

**Comment by sbarex** [comment]
I added support for .tfstate on release 2.1.22. Try if the files are correctly highlighted.
