### ISSUE TITLE
.mdx not handled

### ISSUE THREAD

**Issue by rrroyal** [sbarex/SourceCodeSyntaxHighlight#273]
The `.mdx` ([Markdown + JSX](https://mdxjs.com)) file format isn't handled :/

mdls output:
```sh
$ mdls -name kMDItemContentType -name kMDItemContentTypeTree template.mdx
kMDItemContentType     = "dyn.ah62d4rv4ge8043d2"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge8043d2",
    "public.data"
)
```
<img src="https://github.com/sbarex/SourceCodeSyntaxHighlight/assets/23171377/3e1a4fb3-532f-43fd-b706-b1eba429632d">

**Comment by sbarex** [comment]
This application intentionally does not support the markdown format. Normally for this file it is preferable to see the formatted version rather than the source code.

For the plain `.md` files you use my other app: https://github.com/sbarex/QLMarkdown

**Comment by rrroyal** [comment]
Yup, already using that - I guess I submitted this to the wrong repo, my bad. Would it be possible to implement `.mdx` to QLMarkdown instead?

**Comment by sbarex** [comment]
No, the current rendering engine of QLMarkdown do not support the mdx extension.
