### ISSUE TITLE
.XSD file type handler to change

### ISSUE THREAD

**Issue by marcinK1T4** [sbarex/SourceCodeSyntaxHighlight#276]
Hi,

Please assign correct UTI handlers to .xsd file format. Here is the result from my Sonoma 14.4

```
kMDItemContentType     = "public.xsd"
kMDItemContentTypeTree = (
    "public.xsd",
    "public.xml",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)
```
<img width="983" alt="xsd-inquiry" src="https://github.com/sbarex/SourceCodeSyntaxHighlight/assets/126070018/fd069858-c508-4a57-a3e6-5b712e044450">

**Comment by sbarex** [comment]
Fixed on release 2.1.23 (72).
