### ISSUE TITLE
Install with brew cask?

### ISSUE THREAD

**Issue by gandalfsaxe** [sbarex/SourceCodeSyntaxHighlight#28]
Perhaps you could consider putting this on `brew cask` so one can easily install it, if possible :)

**Comment by sbarex** [comment]
I have to study, I have never used homebrew cask.

**Comment by gandalfsaxe** [comment]
[brew](https://brew.sh/)/brew cask and [mas](https://github.com/mas-cli/mas) is how I install most of my software :)

**Comment by cppguru** [comment]
@gandalfsaxe Since this is a source code highlighter, I assume you code.  How about a PR that adds what is needed for brew casks?  Help @sbarex out?

**Comment by szhu** [comment]
Hi, I'm familiar with Homebrew Cask. I've just submitted a cask for this app:
https://github.com/Homebrew/homebrew-cask/pull/80991

If you want to install it without waiting for the PR to get merged:
1. Go here: https://github.com/Homebrew/homebrew-cask/pull/80991/files
2. Copy the file contents
3. `brew cask create syntax-highlight`, or if you don't know how to use Vim, maybe `EDITOR=nano brew cask edit syntax-highlight`
4. Delete the existing text, paste, save, and close the editor.
5. `brew cask install syntax-highlight`

**Comment by gandalfsaxe** [comment]
@szhu Good stuff, I'll wait for the merge. It was on my (long) todo list, but now you've taken care of it. Nice :)

**Comment by vitorgalvao** [comment]
Merged. This can now be closed.

**Comment by sbarex** [comment]
thank you all. If I have to release new versions do I have to do something to update the cask?

**Comment by vitorgalvao** [comment]
> If I have to release new versions do I have to do something to update the cask?

Yes, the cask will need to be updated as well, but it doesn’t have to be you.

That said, [after a short initial setup](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask) you’ll be able to auto-submit updates to the cask with a single command: `cask-repair --blind-submit --cask-version <new-version-here> syntax-highlight`. That will do everything for you, including opening the PR.

**Comment by jnnkB** [comment]
Maybe there should be a notifcation to run `xattr -r -d com.apple.quarantine "FULL PATH OF THE Syntax Highlight.app (you can drag the file to get the pull path)"` if the running os is Catalina?

**Comment by vitorgalvao** [comment]
> Maybe there should be a notifcation to run `xattr -r -d com.apple.quarantine "FULL PATH OF THE Syntax Highlight.app (you can drag the file to get the pull path)"` if the running os is Catalina?

That’s not the correct (recommended) way to bypass quarantine. Right-click and pick `Open`.

**Comment by cppguru** [comment]
> > Maybe there should be a notifcation to run `xattr -r -d com.apple.quarantine "FULL PATH OF THE Syntax Highlight.app (you can drag the file to get the pull path)"` if the running os is Catalina?
> 
> That’s not the correct (recommended) way to bypass quarantine. Right-click and pick `Open`.

That is the *exact* way the readme says to do it. And open just told me: cannot open, it’s corrupted. Of course it was not corrupted and after xattr worked fine.

**Comment by vitorgalvao** [comment]
> That is the _exact_ way the readme says to do it. And open just told me: cannot open, it’s corrupted. Of course it was not corrupted and after xattr worked fine.

Installed through the repo of Hombrew Cask? If the latter, install with the `--no-quarantine` flag.
