### ISSUE TITLE
Document Boolean about key, isAboutVisible to disable the about message in the footer

### ISSUE THREAD

**Issue by kramred** [sbarex/SourceCodeSyntaxHighlight#280]
Document that there is a Boolean `about` key in `~/Library/Preferences/org.sbarex.SourceCodeSyntaxHighlight.plist`, which sets [`isAboutVisible`](https://github.com/sbarex/SourceCodeSyntaxHighlight/blob/master/XPCService/Settings%2BService.swift#L234) 

The `about` key in `~/Library/Preferences/org.sbarex.SourceCodeSyntaxHighlight.plist` can be set to `NO` and disables the about prompt in the footer with the [`NSHumanReadableCopyright`](https://github.com/sbarex/SourceCodeSyntaxHighlight/blob/master/XPCService/Info.plist) and the prompt:
> If you like this app buy me a coffee

See also:
https://github.com/sbarex/SourceCodeSyntaxHighlight/blob/master/XPCService/Settings%2BService.swift#L234
https://github.com/sbarex/SourceCodeSyntaxHighlight/blob/master/XPCService/Settings.swift#L991-L1007

Turning the app or system off and on again may be required to pick up the changed Boolean `about` key and stop rendering the footer…

![about_](https://github.com/sbarex/SourceCodeSyntaxHighlight/assets/16719551/d58d84fa-e3ea-45c1-95e7-5968f6a7c6c6)

**Comment by sbarex** [comment]
You don't need to mess with the settings plist file. There is graphical interface of the application to do this. The names of the settings in the plist file are not guaranteed to remain consistent between versions.
