### ISSUE TITLE
Support Kotlin (.kt)

### ISSUE THREAD

**Issue by nella17** [sbarex/SourceCodeSyntaxHighlight#289]
It seems that `.kt` extension have two different UTI, but `org.kotlinlang.kotlin-source` use first?
So `.kt` file didn't get highlighted in Finder :(

<img width="718" alt="Screenshot 2024-10-24 at 09 11 40" src="https://github.com/user-attachments/assets/df590634-b78a-4583-8d01-87b22a35f9d9">

**Comment by sbarex** [comment]
Fixed on release 2.1.25.
