### ISSUE TITLE
Request to add support for RAML files

### ISSUE THREAD

**Issue by jrogby** [sbarex/SourceCodeSyntaxHighlight#290]
A simple wish to support .raml-files. They can be highlighted as a normal yaml-file.

Thanks ;)

**Comment by jrogby** [comment]
kMDItemContentType     = "dyn.ah62d4rv4ge81e2prru"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge81e2prru",
    "public.data"
)

**Comment by sbarex** [comment]
Implemented on release 2.1.25.
