### ISSUE TITLE
hey, I would like to buy you a coffee, and can you help remove the footer at each prevew window?

### ISSUE THREAD

**Issue by f1ynng8** [sbarex/SourceCodeSyntaxHighlight#297]
I don't like this footer at everywhere but I would like to buy you a coffee 😄 
<img width="769" alt="image" src="https://github.com/user-attachments/assets/12180b6e-6f4d-4d39-b16e-2cebb05d7c61" />

**Comment by sbarex** [comment]
On the main app, in the view menu, select `show advanced settings`. Then in the general tab there is the switch `Show about info`.

<img width="1142" alt="Screenshot 2024-12-24 alle 09 05 40" src="https://github.com/user-attachments/assets/09008ef5-ba05-420e-9db2-cb9f7edb75ba" />

**Comment by f1ynng8** [comment]
It works, Thank you and the coffee is coming.
