### ISSUE TITLE
Problem highlighting .tex files

### ISSUE THREAD

**Issue by shmulvad** [sbarex/SourceCodeSyntaxHighlight#30]
I have trouble highlighting .tex-files. All other files seem to work without problem. When running the command specified in the README I get the following results:
```shell
$ mdls -name kMDItemContentType -name kMDItemContentTypeTree test.tex
kMDItemContentType     = "dyn.ah62d4rv4ge81k3p2"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge81k3p2",
    "public.data"
)
```

When I try to drop a .tex-file in the Inquiry window the output is the following:
![output](https://i.imgur.com/maU825v.png)

If any more info is needed to debug, please let me know.

**Comment by sbarex** [comment]
On the specific settings, on the list of available syntax you must see two rows for the tex file. They are both grayout?

On your system the tex file appear to be handled by a dynamic uti. I can add this uti on the supported list but on other system i suppose it is not recognized.

**Comment by shmulvad** [comment]
I don't know if tex-files are handled in a weird way on my system. I just recently set up a new computer. LaTeX was installed with `brew cask install mactex-no-gui`.

I only see this when searching for "tex":
![tex-search](https://i.imgur.com/FB5YUrr.png)

If I try to open a tex-file directly in the application I get a message that it can't be opened (other editors like Sublime, VS Code, Vim, etc. open them without a problem):
![error-open](https://i.imgur.com/IXWJaKM.png)

**Comment by sbarex** [comment]
Are you use the last version (beta 19) ?

**Comment by shmulvad** [comment]
I should be. It says "Version 1.0 (19)"

**Comment by sbarex** [comment]
very strange... I hope to release a new version in a few days. I try to add a bugfix also to this problem.

**Comment by sbarex** [comment]
Please try the new release (1.0.b20) to check if the problem is resolved.

**Comment by shmulvad** [comment]
Yes, it works now. Thank you very much!
