### ISSUE TITLE
Apperance settings: consider separate font sizes for QuickLook and Finder preview

### ISSUE THREAD

**Issue by rubjo** [sbarex/SourceCodeSyntaxHighlight#35]
If possible, I would like the Finder preview font size to only be a fraction of the QuickLook font size.

<img width="1290" alt="Skjermbilde 2020-06-08 kl  09 58 24" src="https://user-images.githubusercontent.com/42270947/84006226-aa7c7000-a96e-11ea-8a65-f4cacc9ebf35.png">

Thanks for making this, it's really useful!

**Comment by sbarex** [comment]
Sorry but I don't understand your request.
Yuo can customize the font (family and size) from the appearance settings.

**Comment by rubjo** [comment]
Yes, I know, and that's fine, but what I would like is to have the Finder preview to use a smaller font than the QuickLook popup, like in this mockup:

![mockup](https://user-images.githubusercontent.com/42270947/84007628-021bdb00-a971-11ea-8d33-f1dfb5ca816e.jpg)

**Comment by sbarex** [comment]
I think it is not possible because Apple does not provide an API to know in which context the ql preview is displayed.

**Comment by rubjo** [comment]
Ah, just assumed that it would be possible. Will dial down the font size a bit instead then. Feel free to close. :)
