### ISSUE TITLE
Compatibility with macOS Big Sur

### ISSUE THREAD

**Issue by sbarex** [sbarex/SourceCodeSyntaxHighlight#37]
The application seems to work with the current beta of Big Sug. But the finder quicklook extension don't works.
To solve, you must add the application on the System Preferences, Securtity & Privacy, Privacy, Full Disk Access.

![Screenshot 2020-06-26 at 11 43 45](https://user-images.githubusercontent.com/1948940/85890985-abc2ef00-b7ee-11ea-8df1-656c5977d767.png)

In the first tests some formats of system formats that were not recognized in Catalina now seem to work with the quicklook extension:
- xml, html: still use the default quicklook generator
- plist: use the highlight extension

**Comment by destari** [comment]
I tried this as well, and even though I have it enabled, quicklook previews simply show the spinning indicator.

**Comment by destari** [comment]
Beta 6

**Comment by destari** [comment]
Also, I used the latest pre-release binary.  Perhaps I should build it on my own and try it?

**Comment by sbarex** [comment]
After the first beta I didn't have time to try the next ones. As soon as I have a way I'll do a check. Only the quicklook don't works or also the main app?

**Comment by destari** [comment]
Main app works great, just the quicklook shows the spinner indefinitely.  I can take a poke at it later too

**Comment by rubjo** [comment]
@destari In Global settings, try switching Output mode to RTF. That worked for me.

**Comment by YotrolZ** [comment]
Hi! I found that on the official Big Sur system, the html still cannot be displayed normally, I hope to get your help!

**Comment by sbarex** [comment]
I think that for at least a couple of weeks I will not be able to update to big sur, have patience, as soon as I can I try to check the problem.
