### ISSUE TITLE
Glance

### ISSUE THREAD

**Issue by xiruizhao** [sbarex/SourceCodeSyntaxHighlight#39]
Hi, I was using your app but recently found about [Glance](https://github.com/samuelmeuli/glance), which also supports syntax highlighting source code files (via Go library [Chroma](https://github.com/alecthomas/chroma)). Glance is notarized and supports many other file types (markdown, .zip, .ipynb, .csv). If you are burdened with maintaining this repo, you can ask users to switch to Glance.

**Comment by sbarex** [comment]
Thanks for the report, I did not know Glance.
I think my application is more for geek. It allows you to choose between various themes, to have a theme for each file format, to apply preprocessors (to decompile / convert / beautify... the source code).
Furthermore, I am not interested in managing other formats (markdown, archive, etc.) apart from the source codes.
My application was born as a test to bring the old (and glorious) [QLColorCode](https://github.com/n8gray/QLColorCode) qlgenerator to the new extension system introduced by Catalina.
However Glance seems to me an interesting application and I will study it. 
Thank you!
