### ISSUE TITLE
Consider Renaming the Targets

### ISSUE THREAD

**Issue by alexclst** [sbarex/SourceCodeSyntaxHighlight#4]
Right now the app, extension, and XPC service are all named variations of **QLExtension** or in the case of the XPC Service, **XPCService**. The identifiers are also all variations of **sbarex.QLExt**. There are a number of issues with this that I see as both a user and someone who has written a few Mac and iOS apps:

1. The name of the extension is way too generic. **QLExtension** could mean anything when seen in the context of the Extension pane of System Preferences. You, and I’m happy to come up with suggestions too, should come up with a more unique name. Maybe **SB Source Code Preview**, or even take on **QLColorCode** as the name? The name, and actually also icon, should be unique and make sense in the main context that it appears to users. In the case of a Quick Look Extension, that is in the Extensions pane of System Preferences, where it should be named something that clearly states what it will provide Quick Look support for.
1. The app being named **QLExt** is too generic as well. Once you figure out a name for the extension, the app can be named pretty much the same thing in all likelihood.
1. **XPCService** is a terribly generic name for an XPC service. These are not services always specific to the context of your project, as they are separate executables (the whole reason this one exists). Similar to the above, it should inherit the name you choose for the extension, just with **XPC Service** added to the name. Since macOS may use the name elsewhere, it should clearly say in the name that it is related to this app.
1. Although bundle identifiers can be pretty much anything, the convention (and this may be enforced by the App Stores) is to use a reverse URL. For example, my apps all use **net.tenseg.ProductName**, since my professional website is at [tenseg.net](https://www.tenseg.net). Having just **sbarex.ProductName** isn’t as conventional as, say, **com.sbarex.ProductName**. Making this change sooner rather than later, if you do, is best since it’ll be in effect resetting everyones preferences with the new sandbox containers the new bundle identifiers will be using. But I can’t imagine too many folks, and even fewer or aren’t developers of some flavor, are using this Quick Look extension yet, given how recently you shipped the first build and put up this repository.

I admit that none of these are critical changes. But they are changes I suggest to help bring the app and extension into better line with conventions of macOS apps. Renaming the extension itself, and maybe figuring out a code-evoking icon for it, also help to clarify what it is in System Preferences.

**Comment by sbarex** [comment]
Thanks for your suggestions.
I am not an apple developer and many aspects are new to me.
I then updated the file names, targets and identifiers.

For now i haven't been able to change the title of the application on the dock icon.
