### ISSUE TITLE
support for .Vue files

### ISSUE THREAD

**Issue by CrisGraphics** [sbarex/SourceCodeSyntaxHighlight#40]
Could You please add support for .vue files?

<img width="711" alt="inquiry-format-vue" src="https://user-images.githubusercontent.com/16305374/88639154-bfe36000-d0bc-11ea-8458-71c331a26a34.png">

```
kMDItemContentType = "dyn.ah62d4rv4ge81q7pf"
```

Many thanks!  🙂

**Comment by sbarex** [comment]
Support added on the new relase 1.0.b26.

**Comment by CrisGraphics** [comment]
That was quick! Many many thanks! It's much appreciated! :) 🙌🏼
