### ISSUE TITLE
do not open source files with app

### ISSUE THREAD

**Issue by zhyiyu** [sbarex/SourceCodeSyntaxHighlight#41]
I use the app and it works great! However, when I double click a file, like a Python script, it is opened with `Syntax Highlight.app`. I, however, wanted to open the script with Visual Studio. Could we add the option that lets people choose not to open source files with `Syntax Highlight.app`?

Thanks!

**Comment by sbarex** [comment]
In a furure release I will remove the ability to open source files with the application (it was a function used for debugging purposes). For now you can assign a file to a specific app: select the file on the finder, then press cmd-i, then on the "open with" section choose the application, then click the button to apply the set to all files of same type.

**Comment by sbarex** [comment]
Implemented on release 1.0.b27.
