### ISSUE TITLE
Enhancement: Suggested merge/consolidation of 2 great QL processors sbarex's SourceCodeSyntaxHighlight & Samuel Meuli's glance

### ISSUE THREAD

**Issue by taw123** [sbarex/SourceCodeSyntaxHighlight#42]
While looking for replacement (or details on reenabling QLstephen & QLcolorCode in 10.16) I stumbled upon SourceCodeSyntaxHighlight which builds on the QLcolorCode and adds a great customization UI and works great after downloading from git and clearing quarantine (not notarized) 

Samuel Meuli's glance is already posted in the App Store and supports many of the same formats (code coloring) and adding archive viewing, and some other types but dosen't seem to (easily) support altering code coloring. Since it is actually built on a different open source project my guess is I COULD dig into the pkg and alter it as I wish but it seems there is a POTENTIAL to see the best of both worlds here and HOPEFULLY minimize duplicate of efforts.... 

IF you two might be interested perhaps the two very different code bases could be merged/integrated over time so as not to bifocate efforts? I am going to post the same discussion on both forums to start the suggestion. Thank you BOTH for your efforts from a former long time Apple veteran (Evangelism and Engineering), you were always the reason I enjoyed working in WWDR 👍

--Tom

Link to related issue: [https://github.com/samuelmeuli/glance/issues/51](url)

**Comment by sbarex** [comment]
Close for now. Glance is now archived.
