### ISSUE TITLE
Text files with custom extension are not shown

### ISSUE THREAD

**Issue by danielporto** [sbarex/SourceCodeSyntaxHighlight#43]
I have a few log files that have custom extensions such as ".err"  ".out"  ".trace"...
these are regular text files, usually capture output of scripts to stderr and stdout etc, to a standardized filename (tags, timestamps, etc.. compose the filename plus the extension).
I generate lots of them. 
Changing it now would break compatibility with other parsers that I have and I would prefer to avoid that.

Is there a way to use Syntax Highlight to preview it? 
here is the output of mdls 

mdls -name kMDItemContentType -name kMDItemContentTypeTree oc-on-v1.4.1-cas2-orderers3-peers2-clients1__hyperledger__blockchain-0001-ca10-p8765-o432-c12s1__saturn1__4.15.0-112-generic__intel_pstate__powersave__600s__1599151912____caliper_worker.err

kMDItemContentType     = "dyn.ah62d4rv4ge80n6xw"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge80n6xw",
    "public.data"
)

The only thing different about the content of this file is that it has some special caracteres generated due to colored output of some tools (like those generated by git):
```
020.09.03-16:54:57.521[32m info [39m [caliper] [cli-launch-worker] 	Set SUT type: fabric
2020.09.03-16:54:57.524[32m info [39m [caliper] [messenger.js] 	Creating messenger of type "mqtt-worker"  for SUT fabric
2020.09.03-16:54:57.594[32m info [39m [caliper] [mqtt-worker-messenger] 	Initializing MQTT messenger ... 
2020.09.03-16:54:57.699[32m info [39m [caliper] [mqtt-worker-messenger] 	fabric worker connected with mqtt clientId mqttjs_0155c1e4
2020.09.03-16:54:57.699[32m info [39m [caliper] [mqtt-worker-messenger] 	fabric worker with mqtt clientId mqttjs_0155c1e4 subscribing to topic "master/update"
```
These characters could be ignored and dropped out without problems.
Is there a way to add these custom formats? Or default to text view?

**Comment by sbarex** [comment]
I'm not sure it's appropriate to handle formats with such a generic extension that could be generated by different programs using different syntax.

**Are there any opinions of other developers?**

The special characters in your files are escape sequences used to see colored text on the terminal.

**Comment by bsiegel** [comment]
It would be amazing if there were a way to register new file extensions and associate them with a certain syntax highlighting. But as far as I'm aware, that would involve editing the app's plist and adding new associations, not sure if that is doable.

If not, as a compromise maybe we could solicit a list of extensions that folks commonly want to view as text and add those manually to the app's support.

**Comment by sbarex** [comment]
Sorry, I try vary solution to allow a way to add at runtime custom extensions but this require to edit a plist inside the app extension. This operation in not allowed by the OS. You cad edit the plist with an external tool but this break the code signature and the app stop working.
