### ISSUE TITLE
ts file not showing via the quicklook, is there a workaround

### ISSUE THREAD

**Issue by AddictArts** [sbarex/SourceCodeSyntaxHighlight#44]
Sorry to post this, but I looked and didn't see any info other the vague readme mention. I was hoping there is a workaround or a way to handle dot ts files? Thanks

**Comment by AddictArts** [comment]
```
kMDItemContentType     = "public.mpeg-2-transport-stream"
kMDItemContentTypeTree = (
    "public.item",
    "public.movie",
    "public.audiovisual-content",
    "public.mpeg-2-transport-stream",
    "public.data",
    "public.content"
)
```

**Comment by sbarex** [comment]
sorry, but this is not a limitation of my app, but Apple has reserved some formats for which it is not possible to set a quicklook preview. There is no list of reserved formats, but empirically it has been understood that at least the formats .ts, .plist, .xml, .dart, .jpeg, .png, .gif, .tiff...

**Comment by AddictArts** [comment]
Thanks, would you be willing to update the Readme? I thought this was the case; However, the Readme kinda implies we can report to you a missing type, it doesn't make it clear that these will not be supported types. In addition the UI lists them, further making it confusing.

Your app is amazing and I appreciate all that you have done. I hope this simple suggestion keeps you from having to respond to this kind of non issue. Safe and best wishes.
