### ISSUE TITLE
scrolling does not work if focus is not at quick look window

### ISSUE THREAD

**Issue by zhyiyu** [sbarex/SourceCodeSyntaxHighlight#46]
I found if the focus of the system is not at the quick look window, then scrolling will cause the quick look window to become **empty** 

![quick look](https://user-images.githubusercontent.com/26550166/99138822-8dc12400-2601-11eb-90e4-4e5c0acf003f.gif)

**Comment by sbarex** [comment]
very strange, but it doesn't seem like my code. After formatting the code, its display is delegated to a webkit window or to a text field. 
In the preferences what output mode did you choose, html or rtf? 
Generally it seems to me that the rtf option is more stable and less expensive.

**Comment by zhyiyu** [comment]
You are right, switching the mode to `rtf` solves the issue!

**Comment by zhyiyu** [comment]
If `rtf` works better, shall we maybe make it the default?

**Comment by sbarex** [comment]
Yes, in the next release I will set rtf as predefined output mode.
