### ISSUE TITLE
Cannot worked in macos 11.01

### ISSUE THREAD

**Issue by lonelygo** [sbarex/SourceCodeSyntaxHighlight#48]
OS： macOS 11.0.1
app：1.0.b27

![image](https://user-images.githubusercontent.com/8328467/99225367-e91e2c80-2822-11eb-8dad-72eaca41717d.png)

I have tried several files, e.g. py, go, html, xml, yaml .

![image](https://user-images.githubusercontent.com/8328467/99225731-7c576200-2823-11eb-880d-f6720bc47a3f.png)

**Comment by sbarex** [comment]
Have you looked at [this issue](https://github.com/sbarex/SourceCodeSyntaxHighlight/issues/37)?
Yuo must grant full disk access to the application.

**Comment by yazver** [comment]
OS： macOS 11.0.1
app：1.0 (27)
When open quickview any supported file, content is not showed. 
<img width="922" alt="Screenshot 2020-11-17 at 19 00 44" src="https://user-images.githubusercontent.com/12373036/99389050-0b8a7580-2909-11eb-91f6-0d0d0b2c7a9c.png">

**Comment by sbarex** [comment]
Try to set the output mode to rtf.

**Comment by yazver** [comment]
> Try to set the output mode to rtf.

It's work.

**Comment by sbarex** [comment]
I have to investigate the varius problems with html output...

**Comment by raphaelgurtner** [comment]
Is there any advantage to html output? is it faster or could you ditch html output alltogether?

**Comment by sbarex** [comment]
Normally the html and rtf output are equivalent.
But there are two features supported only by html:
- add a custom css style sheet to change the default settings of the selected theme;
- interactive preview (with js enabled) in combination with specific lua plugins. 

By default there are no plugins active that add interactivity to the code. Also interactive preview prevent to drag the QL windows clicking inside it. And I suppose break the Apple interface guide (QL is only a static preview).

**Comment by sbarex** [comment]
See this [general issue about html preview](https://github.com/sbarex/SourceCodeSyntaxHighlight/issues/52).

**Comment by sbarex** [comment]
See [rel 1.0.b29](https://github.com/sbarex/SourceCodeSyntaxHighlight/releases/tag/1.0.b29) for a temporary fix for the html output mode.
