### ISSUE TITLE
Display error on Big Sur

### ISSUE THREAD

**Issue by nella17** [sbarex/SourceCodeSyntaxHighlight#49]
When in light appearance, top side bar on left display dark background and black text.

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/14134195/99497260-9ffbe300-29b0-11eb-89b0-632999f50cc9.png">

**Comment by sbarex** [comment]
Thanks for the report, in the next release I fix it.

**Comment by sbarex** [comment]
I hope is fixed on last release ([rel 1.0.b29](https://github.com/sbarex/SourceCodeSyntaxHighlight/releases/tag/1.0.b29)).
