### ISSUE TITLE
scroll bar not working

### ISSUE THREAD

**Issue by williamjin1992** [sbarex/SourceCodeSyntaxHighlight#50]
When quick looking the code which exceeds the window size, the scrolling function of trackpad/magic mouse/mouse of other brand are not working, and the scroll bar cannot be dragged by the mouse. But this is not all the case, sometimes it works.
After shut down syntax-hightlight in task manager and restart, it works.
I'm using the rtf mode and the issue happens both in light and dark appearance, system is macOS Big Sur 11.0.1.
Thanks.

**Comment by sbarex** [comment]
thanks for reporting, as soon as I can install the new macos I will try to fix the bug.

**Comment by sbarex** [comment]
It appears that Apple has changed the behavior of the quicklook window. On Catalina it was necessary to intercept the mouse actions to allow the dragging of the window and the opening of the file. Now Big Sur manages these aspects independently, but apparently does not allow the use of the scroll bar by clicking and dragging. It works instead by swiping with two fingers on the trackpad.

**Comment by williamjin1992** [comment]
> It appears that Apple has changed the behavior of the quicklook window. On Catalina it was necessary to intercept the mouse actions to allow the dragging of the window and the opening of the file. Now Big Sur manages these aspects independently, but apparently does not allow the use of the scroll bar by clicking and dragging. It works instead by swiping with two fingers on the trackpad.

Yes I've tried swiping with two fingers on the trackpad or magic mouse, but it doesn't work either. This situation can be solved after completely shut down the two process of syntax-hightlight in _activity monitor_ and open a new quicklook window.

**Comment by sbarex** [comment]
In my case also restarting the process do not resolve the bug...
My app on Big Sur do not handle the mouse action I think is a bug of the os...
