### ISSUE TITLE
Big Sur: missing preview when using html output mode

### ISSUE THREAD

**Issue by sbarex** [sbarex/SourceCodeSyntaxHighlight#52]
In the settings, if you set the html output mode the preview most time do not works. Also **on Big Sur never works**.
**Please set the rtf as output mode (the current release set rtf as default output mode for new installation).**

The problem appear to be related to the entitlements ignored by Big Sur for the quicklook extension.
I am evaluating solutions, for example using the deperecated `WebView` api which works without problems.

When the preview is opened the webkit show this errors:
```
Syntax Highlight Quicklook Extension[13739:455301] [Process] 0x7f8cbc029620 - [pageProxyID=5, webPageID=6, PID=0] WebPageProxy::processDidTerminate: (pid 0), reason 3

Syntax Highlight Quicklook Extension[13739:455301] [Loading] 0x7f8cbc029620 - [pageProxyID=5, webPageID=6, PID=0] WebPageProxy::dispatchProcessDidTerminate: reason = 3

Syntax Highlight Quicklook Extension[13739:455301] [Process] 0x7f8cbc029620 - [pageProxyID=5, webPageID=6, PID=0] WebPageProxy::tryReloadAfterProcessTermination: process crashed and the client did not handle it, not reloading the page because we reached the maximum number of attempts
```
I have also checked the source of webkit, and the main problem is the error:
```
com.apple.WebKit.Networking.Development[96084:1414561] Application does not have permission to communicate with network resources. rc=1 : errno=22
```
generated by `XPCServiceInitializerDelegate::checkEntitlements` on `XPCServiceEntryPoint.mm`.

**Comment by sbarex** [comment]
The problem exists also with signed and notarized app.

**Comment by sbarex** [comment]
For now the problem on Big Sur is "resolved" with the [rel 1.0.b29](https://github.com/sbarex/SourceCodeSyntaxHighlight/releases/tag/1.0.b29) using the deprecated `WebView` component.

**Comment by neoneye** [comment]
Your recommendation `rtf as output mode` is excellent. Now things works after upgrading to Big Sur.

Thanks for this invaluable project, I use it everyday for highlighting rust, swift, ruby files.

**Comment by sbarex** [comment]
Latest release (1.0.b31) has a temporary workaround for the html bug on Big Sur. But the WebKit inside a Quick Look preview il very buggy! Best to use the rtf.

**Comment by hazarek** [comment]
> Your recommendation `rtf as output mode` is excellent. Now things works after upgrading to Big Sur.
> 
> Thanks for this invaluable project, I use it everyday for highlighting rust, swift, ruby files.

the default window margin is zero. Impossible to fix this using RTF mode. ( `body.hl { padding: 16px;}` )

https://user-images.githubusercontent.com/36481442/103822313-f0262600-5080-11eb-8e4f-154502c767b1.mov

@sbarex You should increase the default margin (page padding) for RTF and HTML modes

**Comment by sbarex** [comment]
I fix the padding on the next release, but is not possibile to get the _exact match_ padding from html and rtf output.
