### ISSUE TITLE
How to change UTI for Typescript

### ISSUE THREAD

**Issue by finalist-io** [sbarex/SourceCodeSyntaxHighlight#53]
Typescript has the UTI of public.mpeg-2-transport-stream.
I tried adding this:
`public.mpeg-2-transport-stream = { specialSettings = { syntax = "ts";};};`
 to ~/Library/Preferences/org.sbarex.SourceCodeSyntaxHighlight.plist
but it still doesn't work.
How do I fix this?

**Comment by sbarex** [comment]
I'm afraid it's not possible. The .ts extension is reserved by Apple and it is not possible to customize the ql preview. 
So my application is never called to handle .ts files even if it is configured to do so.

**Comment by luckman212** [comment]
Ok, btw I was asking about the current macOS (12.4) — not macOS 13...

**Comment by matux** [comment]
So:
```
❯ defaults read /System/Library/CoreServices/CoreTypes.bundle/Contents/Info.plist | rg -B6 -A6 public.mpeg-2-transport-stream
                );
            };
        },
                {
            UTTypeConformsTo = "public.movie";
            UTTypeDescription = "MPEG-2 Transport Stream";
            UTTypeIdentifier = "public.mpeg-2-transport-stream";
            UTTypeTagSpecification =             {
                "public.filename-extension" =                 (
                    ts
                );
            };
        },
```

Am I correct to assume nothing has changed for 14.2?

And since this is `/System/Library/`, I won't be able to change anything lest I disable SIP which feels a little like trying to kill a spider with a bazooka, correct?

In any case, @sbarex, your ql gen is excellent, been using it forever.
