### ISSUE TITLE
Typo in dialog

### ISSUE THREAD

**Issue by chrismessina** [sbarex/SourceCodeSyntaxHighlight#54]
When accessing the menu item "Open application support folder" for the first time, there is a typo/incorrect grammar in the error message:

<img width="372" alt="CleanShot 2020-12-04 at 16 35 12@2x" src="https://user-images.githubusercontent.com/22610/101228035-d2633c80-364e-11eb-8af4-f47bc3c73e71.png">

**Comment by sbarex** [comment]
Fixed on release 1.0b29. 
Sorry but English is not my native language.
