### ISSUE TITLE
It's impossible to drag files into the "inquiry format" window.

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#58]
The window loses focus (disappears) when I open the folder to drag a file. this window should be minimizable and always stay on top.

![a](https://user-images.githubusercontent.com/36481442/103825441-17332680-5086-11eb-9b0a-c884eda4b5c2.gif)

**Comment by sbarex** [comment]
Ok, fixed in next release.
