### ISSUE TITLE
Add as a Homebrew Cask

### ISSUE THREAD

**Issue by AdamXweb** [sbarex/SourceCodeSyntaxHighlight#65]
Would be nice to add to Homebrew Cask repo.
Not sure if still unable to submit because of 'beta' however the cask file could look like the below

```
cask "SourceCodeSyntaxHighlight" do
  version "1.0.b31"
  sha256 "e.g."

  url "https://github.com/sbarex/SourceCodeSyntaxHighlight/releases/download/#{version}/Syntax.Highlight.zip",
      verified: "github.com/sbarex/SourceCodeSyntaxHighlight/"
  appcast "https://github.com/sbarex/SourceCodeSyntaxHighlight/releases.atom"
  name "Syntax Highlight"
  homepage "https://github.com/sbarex/SourceCodeSyntaxHighlight"

  app "Syntax Highlight.app"

  zap trash: [
     "~Library/Application Scripts/org.sbarex.SourceCodeSyntaxHighlight",
     "~Library/Application Scripts/org.sbarex.SourceCodeSyntaxHighlight.QuicklookExtension",
     "~Library/Application Support/Syntax Highlight",
     "~Library/Caches/com.apple.helpd/Generated/org.sbarex.SourceCodeSyntaxHighlight.help*1.0",
     "~Library/Containers/org.sbarex.SourceCodeSyntaxHighlight",
     "~Library/Containers/org.sbarex.SourceCodeSyntaxHighlight.QuicklookExtension",
     "~Library/Preferences/org.sbarex.SourceCodeSyntaxHighlight.plist",
]
end
```

**Comment by AdamXweb** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version

**Comment by bb** [comment]
https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/syntax-highlight.rb ?

**Comment by ManuelSchneid3r** [comment]
@sbarex @AdamXweb I guess you can close this issue then?

**Comment by sbarex** [comment]
It is still not clear to me how to update the homebrew formula when new versions are released.

**Comment by AdamXweb** [comment]
If you have brew installed, it can create a pull request to bump the version:
https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask
I'll go ahead and update the cask to v2.0.0

**Comment by ManuelSchneid3r** [comment]
@sbarex aint this what `brew upgrade` is there for?

**Comment by ManuelSchneid3r** [comment]
https://github.com/Homebrew/homebrew-cask/pull/104785
