### ISSUE TITLE
[Word wrap: NO] doesn't work.

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#67]
[Word wrap: NO] doesn't work. (HTML mode)

<img width="342" alt="Ekran Resmi 2021-02-10 23 08 21" src="https://user-images.githubusercontent.com/36481442/107565716-0598ed80-6bf5-11eb-803b-0ae548558f84.png">

**Comment by sbarex** [comment]
Fixed on release 2.0.0.
