### ISSUE TITLE
Elixir files (.ex and .exs)

### ISSUE THREAD

**Issue by ahamez** [sbarex/SourceCodeSyntaxHighlight#68]
Hello,

Even though highlight correctly renders `.ex` and `.exs` (it's listed in the supported extensions), Finder displays a generic blank document icon.

Here's the output of `mdls` for `.ex` files:
```
kMDItemContentType     = "dyn.ah62d4rv4ge80n8a"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge80n8a",
    "public.data"
)
```
and for `.exs` files:
```
kMDItemContentType     = "dyn.ah62d4rv4ge80n8dx"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge80n8dx",
    "public.data"
)
```

Anyway, thank you 💯 for this awesome application 👍

**Comment by sbarex** [comment]
Sorry for the delay, I am making some structural changes to the application and i cannot release bugfixes quickly. 

I hope that next week I will be able to release the new version.

**Comment by sbarex** [comment]
Support added on release 2.0.0.
