### ISSUE TITLE
Please add RMarkdown files (.Rmd)

### ISSUE THREAD

**Issue by sebastiansauer** [sbarex/SourceCodeSyntaxHighlight#69]
Please consider adding RMarkdown files, a common source file for data analysis: https://rmarkdown.rstudio.com/ 

Here's the output of `mdls`: 
mdls -name kMDItemContentType -name kMDItemContentTypeTree cholesky.Rmd
kMDItemContentType     = "dyn.ah62d4rv4ge81e5pe"
kMDItemContentTypeTree = (
    "public.item",
    "dyn.ah62d4rv4ge81e5pe",
    "public.data"
)

**Comment by sbarex** [comment]
I don't know `rmarkdown`. `Highlight` does not support it.
I understand that he combines `markdown` syntax with `yaml` and portions of `r` code that are evaluated at render time. 

`Highlight` can format markdown syntax only colorizing the code (so for example the `**` marker would be colored but not bold style applied).
Another my app [QLMarkdown](https://github.com/sbarex/qlMarkdown) can format the standard markdown syntax.
But none of these applications could fully render `rmarkdown` syntax.

A possible alternative would be to create a preprocessing script that converts the `.rmd` file to another format directly supported by `highlight`. However, the problem would remain that the preformatted data would then be shown with the highlighting of the code and not as a rendering of the formatted appearance.

**Comment by sebastiansauer** [comment]
ok; thanks anyhow

**Comment by sbarex** [comment]
If you want I add a little support for `.rmd` files to my [QLMarkdown](https://github.com/sbarex/QLMarkdown/) extension. Please see [this discussion](https://github.com/sbarex/QLMarkdown/discussions/61).
