### ISSUE TITLE
App is unstable, when scrolling the file types, beach ball, or search for "sh" beach ball

### ISSUE THREAD

**Issue by AddictArts** [sbarex/SourceCodeSyntaxHighlight#72]
I've used OnyX to rebuild launch and XPC cache, but when run Syntax Highlight and search for "sh", it shoots the cpu usage up and I. have to force quit, spinning beachball. I am on Max OS Catalina latest updates etc.

**Comment by sbarex** [comment]
there is a strange behavior when the icons of the files are shown in the list on Catalina. In the release 2.0.0 for now I have disabled the icons if you are using Catalina. With Big Sur it should work instead

**Comment by AddictArts** [comment]
Things are worse now, after the update it seems to 100% disabled. All settings are grey.
