### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by aPinix** [sbarex/SourceCodeSyntaxHighlight#74]
Hi guys,

Can you write a little tutorial on how to install this awesomeness?

Thanks in advance

**Comment by sbarex** [comment]
yes, I'm writing version 2.0 with a new simpler interface, a more concise documentation and some faq. 

Copy the application on the Applications folder, then launch it. This should enable the quick look extension. You can check by going to system preferences / extensions / quick look if the application appears and is marked. 

That's it, that's how it should work. If needed by the application you can customize the appearance of the preview.

**Comment by aPinix** [comment]
Sorry, but where can I download the app?

**Comment by aPinix** [comment]
Got it. Thank you
