### ISSUE TITLE
Word wrap not working & resets on quit

### ISSUE THREAD

**Issue by i0ntempest** [sbarex/SourceCodeSyntaxHighlight#76]
Using the latest version 2.0.1, the line wrap option always resets to "Enable only for one line file" upon saving and relaunching.

**Comment by i0ntempest** [comment]
Also where did you get highlight 4.1? The gitlab repo only has 4.0.

**Comment by sbarex** [comment]
Fixed on 2.0.2.

`highlight` 4.1 is a prerelease with a bugfix for the custom css style in the color schema tokens.
