### ISSUE TITLE
doesn't  work

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#8]
html preview works. py files not. 

preferences;

<img width="777" alt="Ekran Resmi 2019-10-26 19 33 46" src="https://user-images.githubusercontent.com/36481442/67622929-05ba8180-f828-11e9-9532-3f2b7854d997.png">

extensions window;
<img width="713" alt="Ekran Resmi 2019-10-26 19 37 40" src="https://user-images.githubusercontent.com/36481442/67622942-21be2300-f828-11e9-83e0-c5ef06206129.png">
<img width="805" alt="Ekran Resmi 2019-10-26 19 34 28" src="https://user-images.githubusercontent.com/36481442/67622950-2f73a880-f828-11e9-9984-741551bf49d3.png">

Catalina 10.15
gatekeeper disabled

**Comment by rileytwo** [comment]
do you have highlight installed?

**Comment by hazarek** [comment]
> do you have highlight installed?

i installed via homebrew
`brew install highlight`

then i download app from release page. and launch it.

**Comment by sbarex** [comment]
html preview don't works with this plugin because macos use your qlgenerator that show the formatted page and not the html code.
The highlight path is wrong in your settings. He must be `/usr/local/bin/highlight`.

**Comment by hazarek** [comment]
> html preview don't works with this plugin because macos use your qlgenerator that show the formatted page and not the html code.
> The highlight path is wrong in your settings. He must be `/usr/local/bin/highlight`.

it's not my fault. The application is setting the path incorrectly. i set manually and it fixed.
<img width="746" alt="Ekran Resmi 2019-10-26 20 04 27" src="https://user-images.githubusercontent.com/36481442/67623273-df96e080-f82b-11e9-85e4-7847688ebfc5.png">

**Comment by rileytwo** [comment]
@hazarek the app was able to find the highlight binary automatically, on my end, but i had highlight installed before i installed SourceCodeSyntaxHighlighter. did you install highlight before or after you installed SourceCodeSyntaxHighlighter?

**Comment by hazarek** [comment]
i first install highlight via homebrew.

maybe related;

> i use default zsh of catalina.
> When I install something with homebrew, I need to restart the terminal to activate it. I don't know why this is happening?

**Comment by sbarex** [comment]
I'm working to embed highlight inside the app to avoid having to install it by hand. Stay tuned…
