### ISSUE TITLE
version numbers broken && infinite update loop

### ISSUE THREAD

**Issue by core-code** [sbarex/SourceCodeSyntaxHighlight#82]
i've downloaded version 2.0.5 but it claims to be version 2.0.4 in the Finder.

this also leads to an infinite update-loop where the newest version will ask to be updated to 2.0.5. if you agree and install the update, it will ask to be updated again. repeat to infinity.

 
<img width="256" alt="Screenshot 2021-05-14 at 13 00 38" src="https://user-images.githubusercontent.com/1261954/118261938-7ed60400-b4b4-11eb-8914-c965f522f471.png">

**Comment by sbarex** [comment]
Fiexd, thanks.

**Comment by core-code** [comment]
thanks for the quick fix
