### ISSUE TITLE
[BUG] Scroll wheel input ignored

### ISSUE THREAD

**Issue by Altair-Bueno** [sbarex/SourceCodeSyntaxHighlight#84]
I cannot scroll using my mouse on the preview generated from SyntaxHighlight using my external mouse. Other previews work fine (PDFs, TXT, RTF,...)

### Useful information

- OS: BigSur 11.3.1
- Mouse: Razer, no additional software
- SyntaxHighlight 2.0.3
- Trackpad seems fine, but mouse input gets ignored and freezes app

### qlmanage -m report

[QLmanageDump.txt](https://github.com/sbarex/QLMarkdown/files/6528784/QLmanageDump.txt)

PS: I summited a [similar issue with QLMarkdown](https://github.com/sbarex/QLMarkdown/issues/69). It has a crash log from console.app it might be interesting to look at

**Comment by sbarex** [comment]
My application does not handle the mouse in any way. 

Scrolling is delegated to the webkit view. I'm afraid this is one of the numerous webkit view problems within the Quick Look preview window. With Apple magic mouse I have not found any problems.

Please try the RTF render engine, which has far fewer problems...

**Comment by Altair-Bueno** [comment]
I tried both the RTF and HTML render engine. Neither of them work with the external mouse. I also noticed that if i scroll down a little using the trackpad, the mouse works on the preview. The external mouse doesn't seem to trigger rendering so thats why it keeps stuck(?). Not sure but it may be related to #50

I'm gonna try killing SH a couple times and see if solves anything

**Comment by sbarex** [comment]
I think that qlmanage handle only the old qlgenerators and not the new quick look extension api.

**Comment by sbarex** [comment]
Are you using an intel or arm Mac?

**Comment by Altair-Bueno** [comment]
Intel mac

**Comment by sbarex** [comment]
I try with three external mouse (a bluetooth Apple magic mouse, a usb USB Apple Mighty Mouse and a HP USB mouse) and the app never crash and scroll correctly. 

From your [crash log](https://github.com/sbarex/SourceCodeSyntaxHighlight/issues/84) the problem seems to be due to a call to the `eventNumber` property of a `NSEvent` object. But for event of type `ScrollWheel` I think that this property is not defined. The documentation warns that an exception is raised when that property is accessed for events that do not define it. 

Maybe it could be a problem with your mouse driver?  Do you have a chance to try other mouse models?

**Comment by Altair-Bueno** [comment]
Ive been trying to replicate this error but QL seems working fine right now. I'll try doing some more testing if appears again

**Comment by Altair-Bueno** [comment]
Hello again. I managed to replicate this error and found a temporal "solution". Then the QL preview is stuck, resize it a bit and move around so it renders properly. Not sure if this behaviour rings any bells to you

### Example using a random .iml i found

https://user-images.githubusercontent.com/67512202/120105068-bbae2600-c157-11eb-9b94-ca9242b2f9be.mov

**Comment by sbarex** [comment]
For the moment it doesn't remind me of anything.

But so I realized that the `iml` format doesn't show syntax highlighting! 

I will fix it in the next release, in the meantime if you want to enable it just follow these steps:
1. in the Preferences, "format" tab, in the search field at the bottom left, access the drop-down menu and uncheck "hide inaccessible". 
2. search for the iml format
3. select the uti format `dyn.ah62d4rv4ge80w5pq`
4. set the syntax to `xml` 

<img width="1153" alt="Schermata 2021-05-30 alle 16 35 25" src="https://user-images.githubusercontent.com/1948940/120108410-4f3a2380-c165-11eb-9db5-bb0f74f8f627.png">

**Comment by Altair-Bueno** [comment]
Thanks! i've enabled it

**Comment by ShaharHD** [comment]
Any possible resolution to the scroll issue?

**Comment by Altair-Bueno** [comment]
Yea, it looks like Monterey fixed this issue. I think it's safe to close this issue for now, and maybe add a little warning on the README

**Comment by ShaharHD** [comment]
> Yea, it looks like Monterey fixed this issue. I think it's safe to close this issue for now, and maybe add a little warning on the README

It worked for me and now stopped working.
are there any trace logs that would help if I get?

**Comment by Altair-Bueno** [comment]
@ShaharHD Try restarting the qldaemon with `qlmanage -r` and see if that works. Also check as sbarex said: use the RTF engine instead (remember to save the settings with <kbd>command+s</kbd>). If none of that works try rebooting

About the logs, i think i took mine by running `qlmanage -m report`, but it is no longer valid argument on Monterey

For me it has been working like a charm since i updated to Monterey, im really glad i can finally use this quicklook instead of `bat file` everywhere 😅

**Comment by ShaharHD** [comment]
Was using RTF all the time (since I started to follow this thread)

`qlmanage -r` didn't help

I'll try rebooting later, but as I said, it worked for a while after upgrading to new OS, but then stopped working. no idea why.

**Comment by sbarex** [comment]
I did not understand what no longer works.

`qlmanage` handle only the old quick look generator and not the extension that use the new API.

Check in the System settings, Extensions, Quick Look, if the extension is enabled.

**Comment by ShaharHD** [comment]
> I did not understand what no longer works.
> 
> `qlmanage` handle only the old quick look generator and not the extension that use the new API.
> 
> Check in the System settings, Extensions, Quick Look, if the extension is enabled.

The extension is enabled (otherwise it won't show AFAIK).

Just to update, after reboot, it is still stable and working.

If it'll "break" again, I'll open a new ticket, so if everything works like it should for @Altair-Bueno, we can close this issue.

**Comment by ShaharHD** [comment]
> > I did not understand what no longer works.
> > `qlmanage` handle only the old quick look generator and not the extension that use the new API.
> > Check in the System settings, Extensions, Quick Look, if the extension is enabled.
> 
> The extension is enabled (otherwise it won't show AFAIK).
> 
> Just to update, after reboot, it is still stable and working.
> 
> If it'll "break" again, I'll open a new ticket, so if everything works like it should for @Altair-Bueno, we can close this issue.

Stopped working again.

could be related to computer going to sleep?

In any case, `Force Quit` and then selecting the`Finder` makes the issue go away (Finder get's launched again)

Any idea to as of why?

**Comment by sbarex** [comment]
I still don't understand what stops working. After a while, scrolling no longer works?

**Comment by ShaharHD** [comment]
> I still don't understand what stops working. After a while, scrolling no longer works?

The entire quickview is frozen.
can't scroll using my logitech or even drag the scroll bars on the side and on the bottom part of the quickview.

**Comment by sbarex** [comment]
Before Monterey, scroll bars did not work (macos bug). What version of macos do you have? 

After the preview freezes, if you try to view another file is it shown? If so, is that also blocked?

Rather than restarting the finder, try with the activity monitor to terminate the "Syntax Highlight Quick Look Extension (Finder)" process.

**Comment by ShaharHD** [comment]
> Before Monterey, scroll bars did not work (macos bug). What version of macos do you have?
Latest, Monterey 12.0.1

> 
> After the preview freezes, if you try to view another file is it shown? If so, is that also blocked?
Different file via this plugin - same issue, different viewer (like preview for PDF or any image file) - no issue.

> 
> Rather than restarting the finder, try with the activity monitor to terminate the "Syntax Highlight Quick Look Extension (Finder)" process.
Will do once it happens again and will update.

**Comment by sbarex** [comment]
Very strange, on my system it never happened.

From the activity monitor do you see any process blocked related to "Syntax Highlight"?

I am developing a specific update for monterey that takes advantage of a new API which should guarantee better performances...

**Comment by ShaharHD** [comment]
> Very strange, on my system it never happened.
> 
> From the activity monitor do you see any process blocked related to "Syntax Highlight"?
> 
> I am developing a specific update for monterey that takes advantage of a new API which should guarantee better performances...

right now no, once it'll get "stuck" again, I'll make sure to capture as much as I can from the activity monitor.
![image](https://user-images.githubusercontent.com/700985/140478164-0d2f9659-9fbe-4e44-afb9-bcc19e523d2d.png)

**Comment by Altair-Bueno** [comment]
@ShaharHD Do you have Logitech drivers installed? It's not the first time my old Razer mouse drivers made macOS behave weirdly

**Comment by ShaharHD** [comment]
> @ShaharHD Do you have Logitech drivers installed? It's not the first time my old Razer mouse drivers made macOS behave weirdly

Yes.
I have logitech options installed.

I have K750 Mac, MX Keys, MX Master 2s, MX Anywhere 2 ... I'm heavily invested in logitech.

**Comment by Altair-Bueno** [comment]
@ShaharHD Try uninstalling those logitech drivers and rebooting the system. Try replicating the issue

**Comment by ShaharHD** [comment]
> @ShaharHD Try uninstalling those logitech drivers and rebooting the system. Replicate the issue

I can do without syntax highlight ... I can't do without the logitech drivers.
All the shortcuts and button mapping ... logitech without their drivers is pain ...

**Comment by Altair-Bueno** [comment]
And do you have any other kind of peripheral you could try? Apple Mouse for example. Just to make sure it's not related to Logitech drivers

**Comment by ShaharHD** [comment]
> And do you have any other kind of peripheral you could try? Apple Mouse for example. Just to make sure it's not related to Logitech drivers

sure thing. will do.

I have apple magic mouse (1st gen) and apple magic trackpad 2

**Comment by ShaharHD** [comment]
> > And do you have any other kind of peripheral you could try? Apple Mouse for example. Just to make sure it's not related to Logitech drivers
> 
> sure thing. will do.
> 
> I have apple magic mouse (1st gen) and apple magic trackpad 2

@Altair-Bueno  @sbarex 
Issue happed again.

Magic Trackpad or Magic mouse - **no affect**
Activity Monitor, shows nothing of the ordinary.
![image](https://user-images.githubusercontent.com/700985/140662433-1c4fab44-da38-41b4-8881-08ac51eff0cf.png)

Opening the `Syntax Highlight` settings panel, doing save and closing - had no affect.
Switching from `RTF` to `HTML`, saving, closing, trying again - had no affect either.

"Force Quit" `Syntax Highlight XPC Render` - **no affect**
"Force Quit" `Syntax Highlight Quicklook Extension (Finder)` - **resolved the issue**

So my guess is for some reason `Syntax Highlight Quicklook Extension (Finder)` get stuck.

Is there any debug mode or logs you want me to enable and get the trace?

**Comment by sbarex** [comment]
The debug setting enable the creation of a colorize.log file in your desktop. But this log is only for the rendering process and not for the view. I think the problem occurs after formatting the file. 

The XPC Render process is used only for rendering process. The Quicklook Extension process handle the view.

**Comment by ShaharHD** [comment]
> The debug setting enable the creation of a colorize.log file in your desktop. But this log is only for the rendering process and not for the view. I think the problem occurs after formatting the file.
> 
> The XPC Render process is used only for rendering process. The Quicklook Extension process handle the view.

@sbarex is it something you can add into another release? to have some more debug information to be logged?

**Comment by sbarex** [comment]
Actually, after my app passes the formatted code to the view end to operate. 

The next version I think it should solve this strange problem that for now has not been reported by others. 

A series of update have accumulated for the new release that are slowing down its release

**Comment by sbarex** [comment]
The new release 2.1.0 uses a new Monterey API. I hope this resolve your problem.

**Comment by ShaharHD** [comment]
> The new release 2.1.0 uses a new Monterey API. I hope this resolve your problem.

I think the issue can be marked as resolved. been using it for the past two weeks with no issues.

Thanks 🥇
