### ISSUE TITLE
Support for Racket source (.rkt) files

### ISSUE THREAD

**Issue by tomyun** [sbarex/SourceCodeSyntaxHighlight#86]
The inquiry window says "supported but not handled".
Here is an output of `mdls` command for [Racket](https://racket-lang.org) source files.

```
kMDItemContentType     = "org.racket-lang.source"
kMDItemContentTypeTree = (
    "org.racket-lang.source",
    "public.text",
    "public.data",
    "public.item",
    "public.content",
    "public.plain-text"
)
```

**Comment by sbarex** [comment]
Sorry, `highlight` does not support the `Racket` language. Unless it has syntax that comes from other supported languages I can't add it.

**Comment by tomyun** [comment]
Racket is a Scheme dialect so syntax highlighting for `.scm` should mostly work.

**Comment by sbarex** [comment]
Extension `.scm` on `highlight` is associated to the `lisp` language. Is it ok also for Racket?

**Comment by tomyun** [comment]
As Scheme is again a Lisp dialect I think it should be fine.

**Comment by sbarex** [comment]
Try the release 2.0.8.

**Comment by tomyun** [comment]
It works with .rkt files now.

<img width="922" alt="rkt" src="https://user-images.githubusercontent.com/906626/120944485-98502180-c6e9-11eb-8a68-a1ddd46a30a4.png">

There are some areas of improvements (i.e. bracket handling, keyword/identifier detection) which could be reported to highlight upstream, but I think it's still much better than nothing. Thanks for taking care of this!
