### ISSUE TITLE
v2.0.8 can't be launched on Big Sur

### ISSUE THREAD

**Issue by ShengChangYang** [sbarex/SourceCodeSyntaxHighlight#87]
When launching v2.0.8, system pop-up an error dialog but v2.0.7 works fine.
<img width="372" alt="Screen Shot 2021-06-09 at 01 23 10" src="https://user-images.githubusercontent.com/13915531/121230223-8f19ad00-c8c1-11eb-9b55-7472b6107836.png">

**Note**: v2.0.8 works fine on Catalina.

**Comment by sbarex** [comment]
do you have download the app from github or updated via autoupdate features?

Try to remove the quarantine flag with this terminal command:

```sh
xattr -cr "/Applications/Syntax Highlight.app"
```

**Comment by ShengChangYang** [comment]
Here's the error message when I open the app from Terminal.

```
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2539, NSUnderlyingError=0x13ff0c5c0 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x13ff0cd50 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 153}}}}}
```

**Comment by ShengChangYang** [comment]
I found the solution. (or maybe a workaround?)

Since I use the M1 mac, this app must (or maybe need to) be opened by Rosetta 2.

So, it works fine after "open using Rosetta" checked.
<img width="377" alt="Screen Shot 2021-06-09 at 04 01 10" src="https://user-images.githubusercontent.com/13915531/121249621-5d134580-c8d7-11eb-91bc-c3f19f2bc30d.png">

The information shows the app is "Universal".

And I check the arch of the app, it shows:
```
$ file /Applications/Syntax\ Highlight.app/Contents/MacOS/Syntax\ Highlight 
/Applications/Syntax Highlight.app/Contents/MacOS/Syntax Highlight: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
/Applications/Syntax Highlight.app/Contents/MacOS/Syntax Highlight (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Applications/Syntax Highlight.app/Contents/MacOS/Syntax Highlight (for architecture arm64):	Mach-O 64-bit executable arm64
```

**Comment by sbarex** [comment]
I have reuploaded the release 2.0.8. Please redownload and test on your M1 machine. Thanks.

**Comment by ShengChangYang** [comment]
This build works fine w/o "open using Rosetta" checked. Thank you!!!

**Comment by sbarex** [comment]
Well, there was a problem creating the zip file.
