### ISSUE TITLE
General Settings Tab Disabled

### ISSUE THREAD

**Issue by exiva** [sbarex/SourceCodeSyntaxHighlight#88]
Everything in the general settings tab is disabled

Syntax Highlight 2.0.8 (40)
macOS 11.4

<img width="997" alt="Screen Shot 2021-06-17 at 3 07 42 PM" src="https://user-images.githubusercontent.com/56931/122458411-c51ff680-cf7d-11eb-9c45-4de01f7cd1d3.png">

**Comment by sbarex** [comment]
try to reset the settings with this command:
```sh
defaults delete ~/Library/Preferences/org.sbarex.SourceCodeSyntaxHighlight.plist
```

**Comment by exiva** [comment]
That worked thanks
