### ISSUE TITLE
Custom color theme is dropped on every app relaunch

### ISSUE THREAD

**Issue by varahash** [sbarex/SourceCodeSyntaxHighlight#89]
Steps to reproduce:
- Open Syntax.app
- Go to Color tab
- Duplicate any existing color theme
- Hit CMD+S to save setttings
- Quit Open Syntax.app
- Launuch Open Syntax.app again

As result, the custom color theme is missing in the Color tab

FYI: I use macOS Big Sur 11.4

**Comment by sbarex** [comment]
Thanks, is fixed on 2.0.8 **build 41**.

**Comment by varahash** [comment]
I've updated to 2.0.8 build 42, but when I try to save theme got the following error:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/6864532/123558756-a2bd8280-d7a0-11eb-977d-082a7559482b.png">

**Comment by sbarex** [comment]
very strange, version 42 did not bring changes to the management of the themes. Try to select the modified theme, then right click, press the alt key and then from the menu select "Reveal on Finder". Check that the file (and the folder containing it) has write privileges

**Comment by varahash** [comment]
The problem that custom is not saved at this time yet, so 'Reveal on Finder' is unavailable. 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/6864532/124386354-ab531300-dce2-11eb-99b0-37f57ca59e34.png">
But I have found the problem. Basically when you install the app for the first time there is no folder created at `/Users/username/Library/Application Support/Syntax Highlight`. So when I try to save custom theme it fails with error I shown in my previous message.
**The workaround**: hit `Save settings` before creating custom theme, that way the folder `/Users/username/Library/Application Support/Syntax Highlight` will be created, and after that saving custom theme will work fine.
To fix this issue you need to check that 'Syntax Highlight' folder exists (and create if not) before saving custom theme.

**Comment by sbarex** [comment]
Bust be fixed on release 2.0.9.
