### ISSUE TITLE
font does not change in RTF mode

### ISSUE THREAD

**Issue by hazarek** [sbarex/SourceCodeSyntaxHighlight#9]
I set font to Roboto Mono 9.0 pt

RTF mode wrong font;
<img width="520" alt="Ekran Resmi 2019-10-26 20 45 51" src="https://user-images.githubusercontent.com/36481442/67623763-cd1fa580-f831-11e9-9560-6f71c73da711.png">

HTML mode correct font;
<img width="522" alt="Ekran Resmi 2019-10-26 20 46 25" src="https://user-images.githubusercontent.com/36481442/67623764-cee96900-f831-11e9-9b9e-eeec569630e3.png">

**Comment by sbarex** [comment]
WKWebview use point for font size but NSTextView use pixel, so the font on webview is 33% bigger.
In the next version I correct this bug.

**Comment by hazarek** [comment]
it's font family not font size. bug is still exist.

**Comment by sbarex** [comment]
The problem is also in last version? Because in my test is not present…
