### ISSUE TITLE
Quick preview does not work for '.kts' files

### ISSUE THREAD

**Issue by varahash** [sbarex/SourceCodeSyntaxHighlight#92]
As I understand the `dyn.ah62d4rv4ge8007dx` should be added to app `Info.plist` file

<img width="928" alt="Screenshot" src="https://user-images.githubusercontent.com/6864532/123558823-fe880b80-d7a0-11eb-8bd2-f2439104f1eb.png">

**Comment by sbarex** [comment]
Fixed on release 2.0.9.
