### ISSUE TITLE
Setting custom theme for Kotlin files '.kt' does not work

### ISSUE THREAD

**Issue by varahash** [sbarex/SourceCodeSyntaxHighlight#95]
When I create a custom theme and try to use it for Kotlin files, It does not work (the default theme is used). I guess it relates somehow to the fact that `.kt` files has two UTIs
<img width="400" alt="kotlin" src="https://user-images.githubusercontent.com/6864532/124387057-c1160780-dce5-11eb-9884-52f452ce69c3.png">
Because if I try to use a custom theme for Swift files it works fine.
<img width="400" alt="swift" src="https://user-images.githubusercontent.com/6864532/124387102-e73ba780-dce5-11eb-9051-6e0195ecf81c.png">

**Comment by sbarex** [comment]
On release 2.0.9 this problem should be fixed.
