### ISSUE TITLE
When import custom theme with 'space' in its name then Quick Preview fails to render

### ISSUE THREAD

**Issue by varahash** [sbarex/SourceCodeSyntaxHighlight#96]
For example import theme `/Users/test/Desktop/Some Theme.theme` (notice file name contains space) and set it as the default theme. When you try quick preview it fails with following error:
<img width="785" alt="error" src="https://user-images.githubusercontent.com/6864532/124428736-befb8980-dd75-11eb-98ea-249ada03a3c3.png">

**Comment by sbarex** [comment]
fixed on release 2.0.10.
