### ISSUE TITLE
`.svelte` support

### ISSUE THREAD

**Issue by probablykasper** [sbarex/SourceCodeSyntaxHighlight#99]
`.svelte` is HTML based, similar to `.vue`.

Syntax documentation: https://svelte.dev/docs#Template_syntax

I don't think it ever breaks HTML syntax, so it could also work to treat it like HTML.

**Comment by sbarex** [comment]
Using the HTML syntax highlighting would only format the tags between the `<` and `>` brackets, but not the `{# ... }` and `{@ ... }` statements.

**Comment by probablykasper** [comment]
True, but I wouldn't mind too much since it's a small part of Svelte files.

**Comment by belafonte** [comment]
svelte support in some way would definitely be great! Have a lot of those ..

**Comment by sbarex** [comment]
It will be implemented in the next upcoming version.

**Comment by sbarex** [comment]
Support added on release 2.1.0.
